(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
var rect; // used to reference frame bounds

// library properties:
lib.properties = {
	width: 600,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.font_wheel = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#444444").s().p("AAAAGQAAAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgFAFAAQAGAAAAAFQAAAGgFAAIgBAAg");
	this.shape.setTransform(8.1,8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#444444").s().p("AgIAGQgCgCAEgEQAEgFACgDQAEgDADAFIACAKIgGAGQgGgCgFgCg");
	this.shape_1.setTransform(5.5,5.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#444444").s().p("AgGAHIgDgKIAHgGIALAFQACABgEAEQgEAFgDADIgCABQgCAAgCgDg");
	this.shape_2.setTransform(10.6,10.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#444444").s().p("AgGAEQgBgFABgEQAAgDADgBIADAAIAIAHIAAAHQgIAEgDABIAAAAQgDAAAAgGg");
	this.shape_3.setTransform(4.6,8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#444444").s().p("AABAKIgIgHIAAgHIAKgFQADgBACAHQABAFgBAEQgBAEgEAAIgCAAg");
	this.shape_4.setTransform(11.5,8.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#444444").s().p("AAAAHQgFgEgDgDQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAgBABAAIACgCIAKgCIAGAGIgFALIgCAAQgCAAgBgCg");
	this.shape_5.setTransform(5.4,10.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#444444").s().p("AgJADQACgGADgFQABgCAFAEQAFAEACACQADAEgFADIgKACg");
	this.shape_6.setTransform(10.6,5.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#444444").s().p("AgFAHQgDAAgBgDIAAgDIAHgIIAHAAIAFALQABACgHABIgEABIgFgBg");
	this.shape_7.setTransform(8,11.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#444444").s().p("AgEAIQgEgIgBgCQgBgEAHgBQAEgBAFABQAFABgBAGIgHAIg");
	this.shape_8.setTransform(8.1,4.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#444444").s().p("AAABSQghgBgYgYQgYgZAAggQABghAYgYQAYgYAgAAQAiAAAYAZQAYAYAAAgQgBAigYAYQgYAYghAAIAAAAgAgmgnQgQARgBAWQAAAWAQARQARAQAWABQAXAAAQgRQARgQAAgXQAAgVgQgRQgQgRgYAAQgVAAgRAQg");
	this.shape_9.setTransform(8.2,8.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAAA+QgZAAgSgTQgTgSABgZQAAgZASgSQATgTAYABQAaAAASASQATATgBAYQAAAagTASQgSASgZAAIAAAAg");
	this.shape_10.setTransform(8.5,8.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(0,0,16.5,16.5);
p.frameBounds = [rect];


(lib.door_inside = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#444444").ss(1,0,1).p("AjPD+IE/BDIBgpAIk1hBg");
	this.shape.setTransform(20.8,32.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#444444").s().p("AjPD+IBqo+IE1BBIhgJAg");
	this.shape_1.setTransform(20.8,32.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-1,-1,43.7,66.3);
p.frameBounds = [rect];


(lib.door_hand = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#444444").p("AgBASQAEABAFgFQAFgFAAgIQABgGgEgGQgDgFgGgBQgEAAgEAFQgFAFgBAHQAAAGADAGQAEAFAFABg");
	this.shape.setTransform(1.4,1.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgBASQgFgBgEgFQgDgGAAgGQABgHAFgFQAEgFAEAAQAGABADAFQAEAGgBAGQAAAIgFAFQgEAEgEAAIgBAAg");
	this.shape_1.setTransform(1.4,1.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-1,-1,7.6,5.7);
p.frameBounds = [rect];


(lib.door_close = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#444444").p("AgOAKQAEAGAIACQAFABAHgEQAGgEABgHQACgGgEgHQgEgGgHgBQgGgCgHAEQgGAEgBAIQgCAFAEAHg");
	this.shape.setTransform(11.1,28.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgCASQgIgCgEgGQgEgHABgGQACgHAGgEQAHgEAFACQAIABAEAHQAEAGgCAFQgBAIgHAEQgEADgFAAIgCAAg");
	this.shape_1.setTransform(11.1,28.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#444444").p("AjPD+IE/BDIBgpAIk1hBg");
	this.shape_2.setTransform(20.8,32.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AjPD+IBqo+IE1BBIhgJAg");
	this.shape_3.setTransform(20.8,32.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-1,-1,43.7,66.3);
p.frameBounds = [rect];


(lib.car_body = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgbACQAEgJAuAHQAJACgJABg");
	this.shape.setTransform(30.8,17.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAYA1QgCgCgBgPQgBgMgJgRQgHgNgCgBIgWgcIgCgFIABgEIgDgHQgDgHAaAaQABADAQAaQAIALACAeQAAAPgCAAIAAAAg");
	this.shape_1.setTransform(85.4,20.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAfAxIgGgCIg7hdQgBgEAEAFIAFAGIA9BWQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAgBAAIgDAAg");
	this.shape_2.setTransform(77.8,8.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbACQgGAAABgCIADgBIA+ABQgtACgNAAIgCAAg");
	this.shape_3.setTransform(58.2,17.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhOAAIAEgBICaADIidAAQgEgBADgBg");
	this.shape_4.setTransform(72.1,17.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAFAZIABgFQABgEgEgQQgBgBgFgLIgGgMQgBgGAIAJIAHAKIAFAUIAAALIgEAHIgBgCg");
	this.shape_5.setTransform(63.6,20.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAEAUQgCAAgDgGQgJgeAKgDIAAAHQgBAIABAFQAIATgDAAIgBAAg");
	this.shape_6.setTransform(3.3,31.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag7ADQAagbAjgEQAqgFAWAEQAUAEgMAIQgYgKgfABQg8ADglA2QAGgOANgOg");
	this.shape_7.setTransform(10.9,22.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgMgYQgHgHgBgFQgBgFAFAFQAGAGANAaQARAcABAPQgXg1gKgKg");
	this.shape_8.setTransform(22.7,26.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#444444").s().p("AgTAXIATgYQAUgaAAACIgEAFQgSAfgCAAQgCAAgGAIIgGAIIAAAAIgBgEg");
	this.shape_9.setTransform(26.1,9.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#444444").s().p("AAAALQgEgJgBgHQgDgMAIAFIADAJQAEAIAAAEQgBAFgDAAIgBAAQgCAAAAgDg");
	this.shape_10.setTransform(27.5,13.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAAALQgEgJgBgHQgCgMAHAFQAIAOgBAHQgBAFgDAAIgBAAQgCAAAAgDg");
	this.shape_11.setTransform(26.9,13.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AglA0QgDgHADgCIAZgYIAuhDQAJgHgFAHQg6BYgEAEIgHAGIgFACIgBAAg");
	this.shape_12.setTransform(28.5,7.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#444444").s().p("AADAyQgGgBgDgHQgGgOAAgRQgBgOAEgMQADgJAJgOIAKgLIgKAUQgDAIgBASQgCAaAMAWQADAFgHAAIgCAAg");
	this.shape_13.setTransform(69.1,29.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#444444").s().p("AAbA7QAHgGgBgcQAAgcgLgWQgJgTgegLIgdgHQAfgBAaAUQARAMAKANQADAGAEASIACA1QAAAFgNAAQgMAAAFgFg");
	this.shape_14.setTransform(16.5,28.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#444444").s().p("AAoAwIgIgWQgDgHgOgQQgOgOgBAAIhjgEQgFAAgBgFIAAgLQAAgGAFgGIAGgFQB1ACAMACQAMABAMAIIAVAfQAWAfADAHQAEALgMAEg");
	this.shape_15.setTransform(64.7,8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#444444").s().p("ABcAAQAAgEgGgGIgHgEIg2gBQgEAAgCADIgCACIAAA7IgPAAIABg9QAAgEgMABQgQACgEAAQgGAAgFACIgGADIgmA6IgVAAQAmg2ACgHQAAgEgHgFIgIgEQAMgQAVgFQALgDAIAAQBrgEALAFQALAFABANIAEBPIgOAAg");
	this.shape_16.setTransform(41.7,8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhfAzQgCgBABgHQACgVAFgNQAKgbAZgNQAjgUAiABQAvABAjAlQAEADgngaQgOgIgPgCQgTgDgYAFQgkAJgQAWQgRAVgIATQgGANgBAHIgBADIAAAAg");
	this.shape_17.setTransform(74.4,24.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AA5BVQgXgwgEgFIgggmIhChpQBCBjACADQADACAQARQAIAJANAUQAEAHALAZIANAeQACAIgCACg");
	this.shape_18.setTransform(79.6,14.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgBANIADggIgBAnQgCgBAAgGg");
	this.shape_19.setTransform(1.9,19.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ag+ABQAFgBA+gCIA9gCIh7AIIgGABQgEAAAFgEg");
	this.shape_20.setTransform(10.5,17);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgKAJIAhgsQAFgHgIAQIgbAuQgLAPgFADIgBAAQgDAAARgdg");
	this.shape_21.setTransform(22.1,18.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgGAZIADgmIADgvQADgWAFAKIgHAiQgFAkAAAJQABATADAyg");
	this.shape_22.setTransform(25.3,22.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AiPBJQgGgBABgEIADgDIEKgFQAOgBAFgTIABhwIABADIADAGIAEBvQAAAEgDAGQgDAEgBABIiMAGIiLAEIgGAAg");
	this.shape_23.setTransform(40.2,24.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#444444").s().p("AjiCwQgFgBgBgbQAAgkgCgHQgDgNgTgRIgSgOQgJgHgQgFQgTgGgNACQhBANgJAxQgFAYAJAYIAFAJQABAHgJADQgLAEgOgPQgLgMgGgOQgEgJAGgLQAEgJAGgEIAGgDQAAAAABAAQAAAAABgBQAAAAAAgBQABAAAAgBIgBgLQgCgDAAgDIABgIQAAgLgCgJQgCgIgDgFQgDgEABgfQABgHAGgEIASgIQAOgGAOgCICGgOQAFAAAMgIQAFgCANgDQAFgBAGgGIAMgKQAzhIADgGQAFgLAHgBIAOgGQAMgFAFgBIAIgBIAFgCIAGgDQACgBAEAAQAHABAJACIDwADQAtAAASAGIAPADQAFABACACQADAEAMAEIAFABIAFABQADACgBAEQAhAuADACIAOAWQAPAWAGAFQANALAbAbQAEAFAGALQADADAEACQAFABACACQACADAEASIAFAaQABANgJAAQgFAAAAAIQAAAEACABIAFACQAEACACACQADAFAAALQABANgMAPQgKAOgLAGQgHAEgCgCQAAAAAAAAQgBgBABAAQAAAAAAgBQABAAAAAAQACgBAGgYQABgEgLgrQgFgLgMgNQgZgYglgEQgmgFggAfQgTATgJAUQgCAGgDAXIgDAdQAAAHgIAAQgFAAgSgEQgNgDiWACIibADIgyAGQgkAFgJAAIgDAAgAhSiSQgRACgNAOIg8BSQgEAEAAAEIAAAEIAUgBQgCgNACgIQADgSAMgEQANgEANAMQAMALAGATIABAFQCdgBALgCQAHAAgBgEIgDhOQAAgSgOgHIgNgDQhnAAgbAEgAhqglIgDgIIgGAIIAJAAgABiiSQgLAGAAAKIACBIIABAIQADAHAKABIC9gBIAJgEQAJgFgEgLQgGgSgng1QgLgLgQgBIh+gEQgFABgFADgAiSg5IgBAHIAPAIIADgCQADgCADACIAJgLIgIgKQgHgGgGAAIgCAAQgHACgCAMg");
	this.shape_24.setTransform(44.9,17.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(0,0.1,89.8,35.3);
p.frameBounds = [rect];


(lib.back_wheel = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#444444").s().p("AAAAGQAAAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgFAFAAQAGAAAAAFQAAAGgFAAIgBAAg");
	this.shape.setTransform(8.1,8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#444444").s().p("AgIAGQgCgCAEgEQAEgFACgDQAEgDADAFIACAKIgGAGQgGgCgFgCg");
	this.shape_1.setTransform(5.5,5.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#444444").s().p("AgGAHIgDgKIAHgGIALAFQACABgEAEQgEAFgDADIgCABQgCAAgCgDg");
	this.shape_2.setTransform(10.6,10.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#444444").s().p("AgGAEQgBgFABgEQAAgDADgBIADAAIAIAHIAAAHQgIAEgDABIAAAAQgDAAAAgGg");
	this.shape_3.setTransform(4.6,8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#444444").s().p("AABAKIgIgHIAAgHIAKgFQADgBACAHQABAFgBAEQgBAEgEAAIgCAAg");
	this.shape_4.setTransform(11.5,8.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#444444").s().p("AAAAHQgFgEgDgDQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAgBABAAIACgCIAKgCIAGAGIgFALIgCAAQgCAAgBgCg");
	this.shape_5.setTransform(5.4,10.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#444444").s().p("AgJADQACgGADgFQABgCAFAEQAFAEACACQADAEgFADIgKACg");
	this.shape_6.setTransform(10.6,5.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#444444").s().p("AgFAHQgDAAgBgDIAAgDIAHgIIAHAAIAFALQABACgHABIgEABIgFgBg");
	this.shape_7.setTransform(8,11.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#444444").s().p("AgEAIQgEgIgBgCQgBgEAHgBQAEgBAFABQAFABgBAGIgHAIg");
	this.shape_8.setTransform(8.1,4.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#444444").s().p("AAABSQghgBgYgYQgYgZAAggQABghAYgYQAYgYAgAAQAiAAAYAZQAYAYAAAgQgBAigYAYQgYAYghAAIAAAAgAgmgnQgQARgBAWQAAAWAQARQARAQAWABQAXAAAQgRQARgQAAgXQAAgVgQgRQgQgRgYAAQgVAAgRAQg");
	this.shape_9.setTransform(8.2,8.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAAA+QgZAAgSgTQgTgSABgZQAAgZASgSQATgTAYABQAaAAASASQATATgBAYQAAAagTASQgSASgZAAIAAAAg");
	this.shape_10.setTransform(8.5,8.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(0,0,16.5,16.5);
p.frameBounds = [rect];


(lib.car = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// back_wheel
	this.instance = new lib.back_wheel();
	this.instance.setTransform(32.8,12.5,1,1,0,0,0,8.2,8.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:-360},6).wait(1));

	// font_wheel
	this.instance_1 = new lib.font_wheel();
	this.instance_1.setTransform(-32.6,13.5,1,1,0,0,0,8.2,8.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({rotation:-360},6).wait(1));

	// car_body
	this.instance_2 = new lib.car_body();
	this.instance_2.setTransform(0.2,0.4,1,1,0,0,0,44.9,17.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(7));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(-44.7,-17.2,89.8,39);
p.frameBounds = [rect, rect, new cjs.Rectangle(-44.7,-17.2,89.8,38.8), new cjs.Rectangle(-44.7,-17.2,89.8,38.9), rect=new cjs.Rectangle(-44.7,-17.2,89.8,39), rect, rect];


// stage content:
(lib.car_ani = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// smoke
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#444444").s().p("AkmCeQATgGAHgFQAKgHAOgeQAMgaAPgEQAHgDAVACQARABAIgGQAEgDAMAEQAOAAAXgdQAIgKgOgXQgOgVAIgKQAOgSARgLQAUgNASACIAZADQAOAAAGgHQAEgEADgNQAGgeAPgYQARgaAYgNQAYgNAZADQAWADAZAPQAYAQANABQALACAhgGQAMgCgJAQQgNAWAIALQAfAmABAPQABAIgEALQACAPAhgDQAlgDAKAJQAFAFAMAEQAOAEAFABQALAIADAQQACAPgHANQgLAWghAOQglARgpACQgqACgmgNQgagJgKgBQgVgDgLALIgHAKIgHAJQgLAOgigCIg0gHQgMgBgPAEQgRAFgNAAQgRAAgWAGIgnALQhzAiibAHg");
	this.shape.setTransform(441.5,62.1,0.145,0.145);
	this.shape._off = true;

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#444444").s().p("AieBTIAIgCIACgBQAIgCADgDQADgDADgGIAGgLIAGgJQADgDAFgCIACAAIAMgBIACAAIAIAAIAFgCQAEgDADgKIABgGIAGgUQACgGADgEIACgDQAGgHAHgEIAIgDIALgCIAJABIAEABIAIgBIADgCQACgCACgGIADgOQADgHAEgGIAHgLQAGgGAIgEQAEgDAFgCQAIgDAIABIAIACIARAHIAEADQAJAFAGABIAJAAIANgBIANgBQAHAAAEADIAKAHIABABQANALACAKIAAABIgBAOIAAAIQgBAJAFAFIACACIAJAEQAIABACACQAEABACAEIADAFIAAACQABAGgCAGIgBACQgDAHgHAFIgKAGIgLAFQgOAFgQABIgKAAQgRAAgPgFIgGgCIgMgDQgGgBgEABQgEAAgEADIgDAEIgEAFIAAAAIgFAFIgFAEQgIAFgNgBIgHAAIgSgDIgCAAIgNgCIgHAAIgHAAIgOADIgIACIgLADIgKADQg5AQhLADg");
	this.shape_1.setTransform(461.4,54.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#444444").s().p("AjyB/IAMgEIADAAQAMgEAFgEQAEgEAGgJIAJgQQAEgKAFgFQAEgGAGgCIADgBQAFgBAOABIACAAQAIAAAFgBQAEgBADgCQAHgFADgQIACgJQAFgTAGgNQAEgIAFgHIADgDQAJgLAMgGIAMgFQAJgCAIAAIAMACIAIABQAHAAAFgCIAEgDQADgDACgKIAGgWQAEgLAGgJQAGgJAGgGQAJgKALgGQAHgEAHgCQAMgEANABIAMADQAMADANAIIAGAEQAOAJAJABQAFABAKgCIATgCQAKgCALABQAJAAAKAEIAQAJIACABQAUAOADARIAAACQABAEgDARIgBAMQgCAQAGAIIADAEQAFAEAJADQALADADABQAHADADAIIACAHIABAEQAAAJgEAIIgBAEQgGAJgLAIQgHAFgIAEIgQAGQgWAHgYACIgPAAQgZgBgXgIIgIgDIgVgEQgHgBgGABQgHABgFAFIgFAHIgGAHIgBABIgHAIIgIAFQgNAGgTAAIgKAAIgagFIgEAAQgMgDgJAAIgLgBIgJAAQgKABgMADIgNAEIgRAFIgQAEQhVAXhwAFg");
	this.shape_2.setTransform(475.7,49.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#444444").s().p("AkkCZIAOgEIAEgBQAPgFAGgEQAFgEAHgLIAKgUQAFgLAGgIQAGgGAGgDIADgBQAGgCASABIACAAQAJABAHgBQAFgCADgDQAJgGADgTIACgKQAGgYAIgPQAFgLAGgHIAEgFQALgNAOgHIAPgGQALgCAKABIAPACIAIAAQAJABAGgDIAFgEQADgDADgNQACgOAGgMQAFgNAHgMQAHgKAHgIQAMgMANgHQAIgEAIgDQAPgEAPACIAPADQAOAEAPAKIAIAEQARALAKABQAHABAMgCQAKAAANgDQANgCAMABQAMABALAEQALADAKAHIACABQAZAQADAVIAAACQABAGgDAUIgCAPQgDATAHALIAEAEQAFAFAMAEQANADAEACQAIAFADAIIADAJIAAAFQABALgGAKIgCAFQgHALgOAJIgSAKIgTAIQgbAIgcACIgRAAQgfgBgcgKIgKgDQgQgFgIgBQgKgBgHACQgIACgGAFIgGAJIgHAJIgBABIgJAJIgKAGQgPAIgXgBIgMAAIgfgFIgGgBQgOgDgLgBIgNgBIgLABQgMABgOADIgQAFIgVAGIgSAFQhnAbiHAHg");
	this.shape_3.setTransform(484.2,46.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#444444").s().p("AkmCeQATgGAHgFQAKgHAOgeQAMgaAPgEQAHgDAVACQARABAIgGQAJgHADgVQALguATgZQAMgRASgJQATgJATACIAZADQAOAAAGgHQAEgEADgNQAGgeAPgYQARgaAYgNQAYgNAZADQAWADAZAPQAYAQANABQALACAhgGQAogHAkAWQAbATACAXQABAIgFAjQgEAaAMALQAFAFAMAEQAOAEAFABQALAIADAQQACAPgHANQgLAWghAOQglARgpACQgqACgmgNQgagJgKgBQgVgDgLALIgHAKIgHAJQgWAeg1gFIgmgHQgZgFgQAAQgRAAgWAGIgnALQhzAiibAHg");
	this.shape_4.setTransform(487,45);
	this.shape_4._off = true;

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#444444").s().p("AlYCbIgFABIACgBIAZgFIA3gOQARgEAGgFQAIgGAMgZQAKgWANgEIABAAQAEgEAFgCQAGgDATABQAJABAHgCQAEgHACgMQAJgqARgTQALgOAPgIIAMgFIAEgCQANgGANABIAFAAIASAEIADAAIABAAIADgCQADgDADgMQAHgaALgUQAPgWAUgLQASgKASAAQAHgCAIAAQAGAAAGABQAUACAWANQAQAKALADIAFACIAQgDQANgCANABIAAAAQANgCAMAAQAXABAUAMIAHAFQAOAKADAMIACAHIgCAQIgDARIgBACQgCALACAHQABAIAFAFQAFADAKADIAHACIAJADQAJAHACALIABAFQAAAJgFAIIgDAGQgGAHgLAHQgJAGgKAEIgLAFIgDABIgLAGIgLAEQgbAKgdABQgaACgZgGIgSgFQgWgHgJgBQgJgBgGABIgDAEIgGAIQgJANgOAGQgUARgmgEQgJAAgYgFQgWgEgNAAQgPAAgTAFIghAJQgsANgyAJQgvAIg3AEIglADg");
	this.shape_5.setTransform(496.2,45.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#444444").s().p("AklB/IAIgBIgJABIAWgEIAJgCIAXgGQAOgDAFgEQAIgFAJgVQAJgTALgCIAHgBQAGgJAGgDQAGgCAQAAIAFAAIACgJQAIgjAOgPQAJgMANgHQAJgDAIgCQAHgFAIgCQALgFAJABIAEABIAIACIACgHQAFgVAMgRQAKgTARgJQASgKASACIAEAAQANgFAOgBIAKABQASACAUAMQAMAHAIADQAOgCAMADIAUgDQAMgCAKAAQAVAAASAJIAGAEQAMAHADAJIABAFIgDANIgEANIAAACQgCAJABAGQAAAHAEADQAEACAIADIAGABIAHACQAIADACALIAAADQABAGgEAGIgDAFQgGAFgKAFIgQAIIgKAFIgTAGQgIAHgNAFIgJAEQgXAJgYAAQgWABgVgEIgPgFQgTgFgIgBIgCAAQgIAKgLAFIgNAFQgRAUgkgDIgdgEQgSgEgLABQgNgBgQAFIgcAIQgkALgqAIQgoAHgtAEIggADgAktB/IAHAAIgIABg");
	this.shape_6.setTransform(505.3,45.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#444444").s().p("Aj/BnIAPgDIgNAAIAWgHIApgMIAHgNQAHgPAJgCQAEgBAKABQAHgOAIgEQADgCAHgBQAHgZALgMQAIgJAKgGQALgEAKAAIAGgGQALgHAKgCIAHgBQAFgPAHgMQALgPANgIQANgIAOABQAIABAIADIAGgEIAFgCQAMgFAOAAIAJABQAQACARAJQAMAHAJACIAGABQAKABAWgFIAUgCQASgBAQAGIAFACQAKAFACAGIABAEIgDAJQgBAEgEAGIAAACQgDAGABAFQAAAFADACQACABAHABIAEABIAGAAQAGADACAHIAAADQAAAFgDAEIgDADIgNAFIgPAHIgJAEQgPAGgNACIgLABIAAAAIgCACQgGALgSAIIgIADQgSAHgUAAQgSABgQgDIgMgEIgTgFIgMAFQgEACgIABIgBAAIgBACIgFAFQgOARgdgCQgGAAgSgDQgOgDgJAAQgLAAgNAEIgWAHQgeAJgiAHQgfAGglADIgZADgAj/BkIACAAIgDAAg");
	this.shape_7.setTransform(514.5,45.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#444444").s().p("AjaBPIAYgEIgOgCQAJgEAIgFIAegNQAFgIAGgBIAMAAIAAAAIAMgEQADgIAEgFQAFgSAJgHQAFgIAIgDQAJgFAIABIAHABQAGgJAIgFIAGgEQADgJAFgHQAIgLALgGQAKgGALABQAJAAALAGIAHADIACgDQAHgIAKgEIAGgBQAJgEAMABIAIABQANACAQAHQAKAFAIACIAGAAQAJABATgEIARgDQAQgBANACIAEABQAIADABADIABACIgEAFIgEAHIgBACIgEAHQAAAAABABQAAABAAAAQAAABABAAQAAAAAAABQACABAEgBIAEAAIAEAAQAFAAAAAFIABACQAAACgDADIgCABIgKADIgOAFIgIADQgPAGgJACQgIACgIgCQgNgBgMgFIgTgHQgFgDgFAAQAAAGADADIAIADIAIADQAFADABAEQABAGgDAFIgBACQgGAIgOAGIgFACQgOAFgPABQgNABgNgDIgKgDIgPgEQgKgBgGAFIgBAEIgEAEQgLAMgZgBIgSgCQgKgCgIAAIgSADIgRAGIggAKIgIAEIgBABQgJAEgKgBIgNgBIgbAEIgTADgAjQBJIAAAAIgBAAgAjQBJg");
	this.shape_8.setTransform(523.6,45.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#444444").s().p("Ai2A2IAGAAIgOACgAiGA1IgRgDIgHACIgSACIAYgEIgLgFQAGgEAGgGQARgOATgIIAKgFIADgEQAEgEAFgBQAHgDAFAAIAIABIAAAAQAFAAABgCQACgBABgEQADgJAFgHQAGgIAHgEQAIgFAHABQAHgBAIAEQAIADADAAIAMgDQAIgCAHACIAEgFQAGgHAJgCIAEAAQAIgDAKACIAHABQALACANAEQAJAEAGABIAGABQAJAAAPgEIAOgDIAYgDIADAAIAIABQgBgBAAAAQgBAAAAABQAAAAgBAAQAAABgBAAIgFAEIgBABIgDACIgCAAIgLADIgHADQgNAGgIACQgGABgIgCQgJgCgKgFIgOgHQgHgDgFABIgFAAQgMACgFAFIgFAFIgDAFIgJANQAAAFADADIAFABIAFACQADABABADQABADgCADIgBACQgDAEgLAFIgDABQgKADgLABQgJABgHgCIgFgCIgLgDQgHgBgFAEIgDACIgCADQgIAIgSAAIgNgBIgMgBIgMADIgHACIAAABIgDAGQgEAGgHADIgBABQgDACgGAAIgHgBgAijAtIAAAAIgBABgAijAtgACwgoIACgCIAEAAIgCABIgDACQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAgAC5gpIgDgBIADgBQABgBAAAAQABAAAAAAQABAAAAAAQAAABAAAAIABABIgDABIgBAAg");
	this.shape_9.setTransform(532.9,45.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#444444").s().p("AhlA0QgKgDgGgEIgCAAIgFgBQgDAAgCADQgCAEgCAAIgEABIgNgBIgEABIAHgDIATgFIAIgDIgCgCIgBAAIAHgNQAKgQANgIQAHgEAIgDQAKgEAJAAQARAAAEgDIAFgGQACgDAEgBQAHgBAKAEIABAAQAHAEAFACQAMAEAFgCQAFgCAAgDIAAgIQABgFAEgHIADgEIAEgEQAFgEAJgDIADgBQAFgBAFADIALAGQAHAGAHACQAFACAGgBIARgGIAGgDQAGgCADABQAFABACADIABACIABADIAAAAIgBAFIgBACIgBACIgBAEQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAABAAIAFAAIAAAAIAGgBQAEAAABADIAAABQAAACgEACIgDACQgHAEgMADIgMADQgLADgJAAIgEAAIgNgCIgUgFIgFgBQgJgCgGABIgDAAQgJABgFAFIgCADIgBAAIgEAGQgEAGgEgBIgCgCIgEgDIgFgFIAAAAQgEgBABgCIABgCQAEgDgCgDQgCgGgIgBIgIAAQgMABgIAHIgDACIgGAGIgIAEIgDABQAEgBAEABQAEACACgCIAIgCQAGgCAFABQAFACAAACIgBAEQAAABAAABQAAAAAAABQAAAAABAAQAAABAAAAIADAAIADAAIACACIgBADIAAABQgCACgHACIgBABIgLACQgGAAgEgBIgEgBIgGgBQgEAAgCABIgCACIgCABQgEADgGABIgBAFIgCAGQgCAFgEADIgBABQgDACgEAAIgHgBg");
	this.shape_10.setTransform(542.6,43.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#444444").s().p("AkwCcQgOgIgFgRQgBgDADgEIAFgHQAMgaAPgFQAHgCAVABIALgBQAGgCAAACQACA/gjAMQgGACgFAAQgIAAgIgFgAi9CLQgegQgGggQgCgOADgYQALgxATgWQAMgRASgJQATgKATACIAZADQAOABAGgIQAEgDADgOQAFgTArAXQAvAcAQgJQALgGgFgLQgIgNgDgJQgNghBBgjQARgJAWAdQAXAgAWgEQAHgBAfgQQAWgLANAIQAJAGACAPIADAaQACAOABAbQADAWANALQAFAFAMADQAOADAFADQALAIADAQQACAPgHANQgLAWghAPQglAQgpACQgqACgmgNQgagIgKgBQgVgDgLALIgHAJIgHAKQgLAOgJgJIgbgtQgHgLAQgKQASgMABgNQACgcgpgIQgogKgVAMQgyAagMBNQgEAfgGAGQgEAFgHAAQgJAAgNgGg");
	this.shape_11.setTransform(552.3,41.9,0.369,0.369);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#444444").s().p("AhWBBIAGgDIACgCIAFgLIACgFQACgFACgDQACgCADgBIABgBIAIAAQAEAAACgBIABgBQADgCACgIIABgDIABgOQAAgEACgEIACgFQADgFAFgEIABgBQAFgEAFABIACAAIAGABQAEAAACgCIABgCIABgFIAAgFQABgJAEgIIAAgBQAFgJAGgFIACgCQAGgFAGABIAEAAQAEABAGAEIADADQAHAGADAAIABAAQADABAJgCIAEgBQAEAAACACIAFAGIACACQAGAHACAGIABAGIAAADQgBAFACAHIAEAKIADAEIACABIAEACIABABIAEABIACADIABAHIAAADQgBAFgCAEIgEAGQgFAFgGADIgKAEQgHACgHABIgKgCQgHgBgFgDIgBAAQgHgDgDABIgDAAIgDABIgCADIgBABIgCADIgCADIgEAEQgHAEgIAAIgFAAIgFgBIgFgBIgCAAIgJgBIgGABIgEABIgIADIgEACQgiAOguACg");
	this.shape_12.setTransform(454.4,54.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#444444").s().p("Ah3BeIAIgDIADgDQADgDAEgMIACgIQADgHADgEQACgEADgCIABgBQADAAAJAAQAFABADgCIACgCQADgEACgMIABgDIADgVQABgFADgGIADgIQAEgIAGgGIACgCQAHgEAHABIACAAIAKABQAFAAADgEIABgDIACgHIAAgHQACgNAFgLIAAgBQAGgNAIgJIADgDQAIgFAJgBIAEABQAHABAHAGIAFAEQAJAJAFABIABAAQAFABAMgDIAGgBQAFAAAFACQAFACAFAEIADADQAHAJADAJIACAIIAAAFIgBAUQAAAKACAGIADAFIADADIAFACIABABIAGACIADAFIACAKIAAAEQAAAHgCAFIgFAJQgFAIgJAGIgNAGQgKADgJABIgOgBQgKgCgIgEIgBAAQgKgFgEAAIgEAAIgFACIgEADIAAABIgDAFIgDAFIgEAGQgIAJgNgBIgGAAIgHgBIgHgCIgEgBQgHgCgFAAIgKABIgGACIgKAEIgGADQgvAUg/AEg");
	this.shape_13.setTransform(463.7,49.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#444444").s().p("AiKBxQAGgCADgCIADgEQADgEAFgOIADgIIAGgOQACgFADgCIACgBQADgBALABQAGABAEgDIABgCQAEgFACgPIABgEIAEgYQACgGADgIIAEgIQAEgKAIgHIACgCQAIgGAIABIACAAIALACQAHABADgGIACgEIACgIIAAgJQADgPAEgNIABgBQAHgQAJgKIAEgCQAJgJAKAAIAFABQAIACAJAHIAEAEQAMAMAGABIABAAQAFAAAPgDIAHgCQAGAAAHADQAGACAFAEIAEAEQAJAJADALIACAKIAAAHIgCAYQgBAMACAIIADAFIAEAEIAFADIACABIAHACIAEAGQACAFAAAHIABAFQgBAIgCAHIgFAJQgGAKgKAHQgIAEgIAEQgKADgMABQgIABgIgCQgLgBgKgFIgBAAQgMgGgEgBIgGAAIgGACQgCABgBADIgBABIgDAGIgDAHIgFAHQgJAKgPAAIgHAAIgIgCIgJgDIgEgBQgJgCgGAAIgLABIgHACIgNAGIgGADQg2AYhKAEg");
	this.shape_14.setTransform(469.2,46.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#444444").s().p("Ai2B3IACAAIAFgCIgCAAIAHgCIAfgMQAJgDADgEQAEgEAGgTIAFgMQADgGAEgCIAEAAQADgFACgBQAEgCAIABIAEAAQACgFABgJQAFggAJgOIAFgJIAHgIQAHgFAHABIABgBIACgBQAFgEAHACIABAAIAGABIADgLQAEgUAGgPQAFgRALgJQAKgJALACIAEACQAJgFAJACQAJACAMAJIABABQAHAGAFADQAJgDAJAEIAJgDQARgEAOAKIADACQAFAFADAFQADAFABAIIAAABIgBAHIgCALIgBAJIgCAJQABAIAEAEQACADAFACIAIAEQACABABADQACAEAAAEIAAABQAAAJgDAIIgCAFQgGAIgHAGIgHAFQgJAGgKACIgDADQgIAGgKADQgIACgIABQgSABgRgIQgJgFgFgBIAAAAIgBACIgDAGIgCAGQgDAEgEADQgGAFgIAAQgKAKgQgDIgPgEQgLgDgHAAQgHAAgKAEIgRAHQgRAIgTAGQgbAIgfADIgTADIgCAAg");
	this.shape_15.setTransform(475.9,45.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#444444").s().p("AipBkIACgBIAPgFIgHABQAJgCAIgEIARgFIACgCQAEgEAFgPQACgGACgEQADgFAEgBQACgBAHAAQAEgJAFgDIAFgCIAAgDQAFgbAHgLIAFgIIAGgGQAHgFAHABIAIABIACgCIAFgGIABAAIADgBIAAgDQADgRAGgNQAGgOAJgIQAHgHAJABQAGABAIAGIAHgFQALgHALACQAJACALAHIACABQAKAIAGABQAGAAAOgEQAQgEANAGIADACQAEADACAEQADAEAAAFIgBACIgBAFIgDAIIgCAGIgBAHQAAAGADACQACACAFACIAGACIADADQABACAAAFIgBABQAAAHgEAFIgCAEIgNANQgDADgEABQgKAGgLAAIgIAAQgFAJgJAGQgIAFgIADQgHACgHAAQgPABgNgGIgEAEQgJAGgOgDIgDgBIgBADIgDAFQgIALgPgCIgOgDQgJgDgGABQgGAAgIADIgOAGQgPAHgQAFQgWAGgbAEIgPACIgCABg");
	this.shape_16.setTransform(480.8,46.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#444444").s().p("AicBQIAHgBIAQgFIgHAAQAGgDAHgFIAOgHIACgGIAEgIQACgEADgBQADgBAFABQAFABADgDQADgDABgJQAEgVAGgJIAEgGIAFgFQAFgEAHABIAHAAQAEABACgDIADgIQACgNAEgLQAGgMAHgGQAIgGAGABQAFABAHAGQAHAGAEAAIACAAIADgDQAGgIAJgEQAKgEALACQAIABALAGIACABQAJAGAHAAQAFAAANgEQAPgEAMADIACABIAFAEQACACgBAEIAAABIgDADIgDAGIgCAEIgCAEQAAAEADABIAEACIAGAAIABACQABAAAAAAQAAABAAAAQAAABAAAAQAAABgBABIAAABQgBAFgFAGIgCAEIgMALQgDABgEAAQgJAFgKgCIgKgBIgQgBIgGgBIAAAEIAAAIIgBAEQgEAJgJAHQgHAEgGACIgMACQgNABgLgGIgLgEQgEgBgEAFIgCAEIgCAEIgCAEQgHAJgOgBIgLgDQgIgCgFABQgFAAgGACIgLAGIgRAHIgFAEIgDABQgFACgGAAIgIABIgVAEIgHABIgHACg");
	this.shape_17.setTransform(485.7,46.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#444444").s().p("AiRA9IAMgDIAMgCIAEgCIgHgCIALgJIAGgEIABgDIAFgCIABgBIAOgIIAAgCQADgQAGgHIADgEIAEgEQAEgDAEABIAGABQADAAACgDIACgFQACgKAEgJQAEgJAGgFQAFgFAGABQAFAAAGAEQAFAFADgBIAIgCQAIgDAIAGIABAAIAEgDIADgDQAGgGAJgCQAKgDAJACQAJABAJAFIACAAQAJAFAGgBQAHAAAKgEQAPgFAJABIACAAIAFABQAAAAAAAAQAAAAAAABQAAAAgBAAQAAABAAAAIgBABIgDACQgDABgBADIgDABIgBABIABABIAEABIAEgBIABAAIgBABIAAABIgHAIIgDADIgMAKIgHADQgJACgJgDIgIgCQgHgCgHAAIgOABQgIgBgEACQgGABgCAGIgBAEIAAACIgBAFIABAEIgBAGIAAACQgEAHgHAFQgFADgFACIgKABQgIABgJgEIgIgDQgFgBgDADIgBAEIgCADIgBACQgHAIgKgBIgJgBIgJgBIgJACIgDABIgDAJQgCAEgDACIgDABQgEACgHgBQgJAAgHgCIgFACIgXAGg");
	this.shape_18.setTransform(490.7,47.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#444444").s().p("AiIAyIAIgCIARgFQgCAEgCABIgEABIgQADgAhaAwQgKgBgHgFIgBAAIgDABIABgCIAAgBIAAAAIAHgLQAJgLAKgHIABgCIACgCQADgCACAAIAKgFIAFgLQADgGAFgEQADgEAEAAQAEAAAEACQADADADgBIAGgCQAGgCAFADQAFgBACABIACABQAAAAAAABQABAAgBAAQAAABAAAAQgBAAgBABIAAAAQAAAAAAABQAAAAAAABQAAAAAAABQABAAABABIgEgBIAAAAIgBAHQAAAFABABIADABIABABIABAAIABAEIgBAEIAAACQgDAEgFADIgHAEIgIABQgHAAgHgCIgFgCQgEgBgCACIgBADIgBACIgBABQgFAGgIAAIAAAAIAAABIgDAJQgCAEgDACIgCABIgEABIgHgBgAAHgEIgCgBQgCAAgDgDIgFgFIgBAAIAAgBIACABIAEACIAIAEIADABIAAAAIgDACIgBAAgAALgGIACgDIADgGIACgFQADgEAFgCIADgCIAAAAIAAAEIAAACIAAAEIABAFQAAADgEADQgDACgEAAIgIgBgABQgcIgCAAQgJgDgIgBQgJgBgIABQgKAAgFAEQACgFAFgDQADgCAHgBIANgCQAGgBAHADIAGADQAIAFAIgBIAGgCIANgJIADgCQAFgFADgBIAAAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAABIgDADIgDABIAAADIABABIAEABIAFgBIAEgBIAAAAQABAAABAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAIgBABIgWAHQgJAEgGAAIgDABQgGAAgGgDg");
	this.shape_19.setTransform(496.1,46.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#444444").s().p("Ah+AyIgBgBIAEgDIALgEIAIgFIAEgDIAEgBIABAAIADgKQAHgPAKgIQAVgMAHABIAHAAQAJgBACgCIACgCIACgEQACgDADAAQAFgBAIAEIADABIAHAFQAMAEAFgDQAEgCgBgEIgBgEIgBgEIgBgCIAAgDQABgFAEgDQADgDAGgDIALgEQAFgBAGADIAGAEQAHAHAHAAQADABACgBIAOgIIACgBQAGgEADABIABAAQABABAAAAQABAAAAABQAAAAAAABQABABAAAAIAAADIgBAEIgCADIABAGQAAABAAABQAAAAAAABQAAAAABABQAAAAAAAAIAEAEIAGABIAEABIABAAQAEABAAAEQABADgDACIgBABQgGAGgNADIgPAEQgGABgHgBIgDAAIgPgCIgRgCQgJgBgFABIgDABQgFABgDAEIgCAEIgDAFIgDADQAAAAgBAAQAAABgBAAQAAAAgBgBQAAAAAAAAIgCgCIgFgEIgEgHIAAAAQgEgDAEgDIABAAQADgBAAgDIAAgCQgDgFgLAAQgKgBgGAEIgEADIgGAFIgGAEIgFAEIACACIgBACQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAABAAIABAAIABABIAAACIgBADIAAAAIgFAEIgFACIgBAAIgCAJIgCAJIgDAGIgCABQgEACgHgDQgMgDgFgKIgEAIIgBADIgDAAIgCAAIgDAAIgCACQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAAAAAIgDAAIgDAAIgGgBg");
	this.shape_20.setTransform(501.4,45.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#444444").s().p("Ai6CAIAAAAIADgBIApgQQAJgEADgDQAFgFAGgVIAFgNQAEgGAEgCIABAAIAEgDQADgCAJABQAFAAADgBQAEgGABgMQAFgiAJgQIAGgKIAIgIQAGgFAGAAQAFgDAGABIACAAIALACIADgDQABgCACgKQAEgVAFgRQAIgSALgKQAKgIALABQAGgBAGABQAKACAMAJIABABQAKAKAHACIAJgCQAHgCAGABIABAAQARgFAQAMIADADQAFAFADAGQAEAHABAIIAAACIgBAHIgCAMIgBAKIAAAKQAAAJAEAFQACAEAGACIAIAFIAEAEQACADABAHIAAACQAAAJgDAJIgDAFQgEAIgHAHIgIAGIgNAGQgIAGgJADQgJACgJABQgTABgRgJQgNgGgEgBIgGAAIgBABIgCAFIgBACIgDAHIgDAGQgDAEgEADQgEADgFACQgKAGgOgCIgRgFQgMgDgHAAQgIAAgKAEIgSAIQgTAIgVAHQgcAHgiAEIgXADIADgBg");
	this.shape_21.setTransform(473.5,45.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#444444").s().p("AiwBtIADAAIALgEIAbgKQAHgDADgDQAEgEAFgRIAFgLQAEgFADgCIAHgBQADgGAEgCQADgCAHAAIACgIQAEgdAJgNIAEgJIAIgHQAHgFAIABIACABIAEgFIABAAQAFgDAHABIAAAAIACgHQACgRAHgPQAHgPAHgJQAJgIALACQAEABAFADIABgBQALgHALACQAKACALAIIABABQALAJAHAAQAFABAOgEQARgFAOAJIADACQAEAEADAEQADAFAAAGIAAACIgBAGIgDAJIgCAIIgBAHQABAHADAEQACACAFACIAHADQABAAAAABQAAAAABABQAAAAAAABQABAAAAABQACADAAAFIAAACQgBAFgEAIIgCAEQgFAIgHAGIgHAFQgLAGgMABIAAAAQgEAEgGAEQgIAGgJADQgHACgIAAQgRABgPgHIgHgDIAAAAIgCAGQgCAEgEADQgHAFgMgBIgBABQgKANgQgDIgQgDQgJgDgGAAQgHAAgIAEIgRAHQgPAHgSAGQgZAGgcAEIgRACIgDABg");
	this.shape_22.setTransform(478.4,45.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#444444").s().p("AijBaIADAAIARgGIgHABIAQgHIAQgHIAGgNQABgGADgDQACgEADgBQADgBAGAAIAFAAQAEgKAEgEIAAgBQAEgYAHgKIAEgHIAGgGQAGgEAGABIAIABQAFAAACgEQACgBABgHQADgPAFgMQAGgNAIgHQAIgGAGABQAHABAIAHIAEADQAGgIAIgDQALgGALACQAIACALAGIABABQAKAHAHABQAGAAANgEQAQgFAMAGIACABQAEACACADQACADAAAFIgBABIgCAEIgDAHIgCAGIgBAFQAAAEADACIAFADIAGABIACADQACABgBAEIAAABQgBAGgEAHIgDAEIgMAKIgHAEQgKAFgLgBIgKgBIgHgBIgBACIgBAEQgEAKgLAIQgGAEgHACIgOADQgMAAgLgEQgGACgKgCIgJgDIgBABIgCAFIgDAEIAAAEQgIALgPgCIgNgDIgNgCIgNADIgNAGQgNAHgPAEQgUAGgYAEIgNACIgDABg");
	this.shape_23.setTransform(483.3,46.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#444444").s().p("AiWBGIANgCIABAAIAMgEIgIgBIANgIIAJgGIABgCIADgHQADgDACAAIAHAAQAFAAACgCQADgDABgIQADgSAGgIIAEgFIAEgFQAFgDAFABIAGAAQAEABACgDIACgHQADgLAEgKQAFgKAGgGQAGgGAHABQAFABAGAFQAFAFAEAAQADAAAIgDQAEgBADABIABgBQAGgHAJgDQAKgEAKACQAJABAJAGIACAAQAJAGAHgBQAGAAAMgDQAPgFAKACIACABQAEABABABQAAAAAAABQABAAAAAAQAAABgBAAQAAABAAABIgBABIgCADQgDABgBADIgDADIgBADQAAAAAAABQAAAAAAAAQABABAAAAQAAAAABAAIAEACIAFgBIABABIAAADIgBABIgGAJIgCAEIgNAKIgGADQgKAEgJgDIgJgBIgPgCQgIABgGgBQgKgCgDACIgEABIAEACIABABIADABQADADAAAEIgBAIIgBADQgDAIgJAGIgLAFIgLACQgLABgKgFIgIgEQgGgBgDAEIgCAEIgBAEIgCADQgHAIgMgBIgKgCQgHgBgEAAQgEAAgGADIgKAFIgFACIgBADQgCADgEADIgDABQgFACgGAAIgOAAIgQADIgNADg");
	this.shape_24.setTransform(488.2,47);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#444444").s().p("AiMA0IAJgDIASgEIgCACIgFACIgTAEgAhfAxQgJgBgHgDIgCAAIABAAIgFgDQAFgDAEgHQAKgJAKgHQADgJAEgFIADgCIADgDQADgDAEABIAFAAQAAAAABAAQAAAAABAAQABAAAAAAQABgBAAAAIACgFIAFgQQAEgIAFgEQAFgFAEABQAFAAAEADQAFAEADgBIAIgCQAHgDAFAFQAEAEABAFIgBAKIAAACIABAAIADgDIADgDIACgHIADgFQADgFAEgCIADgDQAGgEAJgBQAJgCAJABQAJABAJAEIACAAQAIAEAHgBQAGAAAKgEIAUgFIACAAIABAAIABAAIACAAIABgBQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIgCABIgDABIgFADIgDAAIgDADIgCADIgNAJIgGACQgIACgJgEIgHgCQgHgDgHABIgNABQgIAAgDACQgGACgCAGIAAAEIAAACIAAAEIAAAFQgBAEgEACQgFADgIgBIAAACIAAADIgBACQgDAGgGAEIgHAEIgJABQgIABgIgDIgHgDQgEgBgDADIgBADIgBACIgCADQgFAGgJAAIgIgBIgGgBIgBACIgDAKQgCAEgDACIgCABIgGACIgGgBg");
	this.shape_25.setTransform(493.4,47.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#444444").s().p("AiEAyIAHgDIAQgFIAHgEIAAAAIAFgMQAJgPALgIIAOgFQADgDADgBIACAAIAIgCIAHAAIAFAAIACgDIAHgDIgBABIgBACQgCACgFABIgBAAIAAABIADABQADACABACIgBADQAAABAAABQAAAAAAABQAAAAAAAAQABABAAAAIACAAIAAABQACAAgBAAIABAEIgBADIgBABQgCAEgEACIgFADIgIABQgFAAgFgCIgFgBIgBAAIgBACIgBAKIgEAJIgDAGIgCABQgEACgHgCQgKgDgFgFIgCABIgEAAIgDAAIgCADQgCAEgCAAIgEABIgNABgAAHAGIgCgBIgFgDIgFgEQgEgEADgCIABAAQABgBAAAAQABgBAAAAQABgBAAAAQAAgBAAAAIgBgCQgEgDgKABIgJACIACgDQACgDAEAAQAEAAAJAEIADABIAIAEQAMAEAFgDQAEgDgBgDIAAgEIgBgFIAAgBIAAgEQABgFAFgDQACgDAIgBIALgDQAGgCAGAEIAGADQAIAGAIgBQACABADgCIAOgIIABgCQAGgEADAAIABAAQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAACIgCADIgCACIAAAFIABADIAEACIAGAAIADAAIACAAQAAAAABAAQAAAAABABQAAAAAAABQABABAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABIgCABQgGAEgOAFQgIADgHABQgGABgIgCIgCAAQgIgDgIAAIgRgCQgKAAgFADIgDABQgFABgDAEIgCAFIgDADIgDAEIgCABIgBgBg");
	this.shape_26.setTransform(498.7,46.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#444444").s().p("AhyA2IgCgBIgGgCIgBgCIADgCIAHgEIAFgEIACgCIACgCIADAAIACgBIAGgDIAAgBIAAAAIABgBQAAAAABAAQAAAAAAgBQABAAAAAAQAAAAABABIABAAIABgHQAGgRAIgHQAUgMAHAAIAHABQAIgBADgCIABgCIACgEQABgDADAAQAFgBAHAEIADABIAHAFQALAEAFgCQAEgDgBgDIgCgEIgBgEIgBgBIAAgEQAAgEADgEQADgEAGgDIAKgEQAFgDAGAFIAFAEQAGAIAHAAQACABADgBIAOgGIACgCQAGgDADACIABAAQADACAAAEIABADIgBAFIAAAEIAAAIIACAGQACADACABIAGADIAFABIABAAQAEACABAFQABACgDADIgBACQgFAHgMAFQgHADgHABQgHABgHAAIgCAAIgPgBIgQgDQgJgCgEABIgEAAQgFAAgDAEIgCAEIgDAEIgDADQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIgCgCIgEgFIgDgHQgEgEAFgDIABgBQAEgDgBgEIAAgDQgCgEgLgCQgKgBgHACIgEADIgGADIgFAFIgFAFQgEAHgDAJIgBAJIgDAIIgCAGIgCABQgEACgHgDQgJgEgEgIIgDAFIgBABIgCAAIgBABIgCAAIgBABIgBABIgFAEIgBACIgCAAIgCAAIgCgBIgBABIgBAAIgCAAg");
	this.shape_27.setTransform(504,44.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#444444").s().p("AhWBBIAGgDIACgCIAFgLIACgFIAEgIQACgCADgBIABgBIAIAAQADAAADgBIABgBQACgCADgIIABgDIABgOQAAgEACgEIACgFQADgFAEgEIACgBQAFgEAFABIABAAIAHABQAEAAACgCIABgCIABgFIAAgFQABgJAEgIIAAgBQAFgJAGgFIACgCQAGgFAGABIADAAQAFABAGAEIADADQAHAGADAAIABAAQADABAJgCIADgBQAEAAADACIAFAGIACACQAGAHACAGIAAAGIAAADQAAAFACAHIAEAKIADAEIACABIAEACIAAABIAEABIADADIABAHIAAADIgDAJIgFAGQgEAFgGADIgKAEIgOADQgFAAgFgCQgHgBgFgDIgBAAQgHgDgDABIgDAAIgDABIgDADIAAABIgCADIgCADIgEAEQgIAEgIAAIgEAAIgFgBIgFgBIgCAAIgJgBIgGABIgFABIgIADIgDACQgiAOguACg");
	this.shape_28.setTransform(420.2,54.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#444444").s().p("Ah3BeIAIgDIACgDQADgDAFgMIACgIIAGgLQACgEADgCIACgBQADAAAIAAQAGABADgCIAAgCQAEgEACgMIABgDIADgVQABgFACgGIAEgIQAEgIAGgGIACgCQAIgEAGABIACAAIAKABQAFAAADgEIABgDIACgHIAAgHQACgNAEgLIABgBQAGgNAIgJIADgDQAIgFAJgBIADABQAIABAHAGIAFAEQAJAJAFABIABAAQAEABANgDIAGgBQAGAAAEACIAKAGIACADQAJAJACAJIACAIIAAAFIgBAUQAAAKACAGIADAFIADADIAEACIACABIAGACIADAFQACAFAAAFIAAAEIgDAMQgBAFgDAEQgGAIgIAGIgNAGQgKADgKABIgNgBQgKgCgIgEIgBAAQgKgFgEAAIgEAAIgGACIgDADIAAABIgCAFIgEAFIgEAGQgIAJgNgBIgGAAIgHgBIgHgCIgEgBIgMgCIgKABIgGACIgLAEIgFADQguAUhAAEg");
	this.shape_29.setTransform(425.7,49.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#444444").s().p("AiKBxQAGgCADgCIADgEQADgEAFgOIADgIIAGgOQACgFADgCIACgBQADgBALABQAGABAEgDIABgCQAEgFACgPIABgEIAEgYQACgGADgIIAEgIQAEgKAIgHIACgCQAIgGAIABIACAAIAMACQAGABAEgGIABgEIACgIIAAgJQADgPAEgNIABgBQAHgQAJgKIAEgCQAJgJAKAAIAFABQAIACAJAHIAEAEQAMAMAGABIABAAQAFAAAPgDIAHgCQAGAAAHADQAGACAFAEIAEAEQAJAJADALIACAKIAAAHIgCAYQgBAMACAIIADAFIAEAEIAFADIACABIAHACIAEAGQACAFAAAHIABAFQgBAIgCAHIgFAJQgGAKgKAHQgIAEgIAEQgKADgLABQgJABgIgCQgLgBgKgFIgBAAQgLgGgFgBIgFAAQgEAAgDACQgCABgBADIgBABIgDAGIgDAHIgFAHQgJAKgPAAIgHAAIgIgCIgJgDIgEgBQgJgCgGAAIgLABIgHACIgNAGIgGADQg2AYhKAEg");
	this.shape_30.setTransform(428.9,46.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#444444").s().p("Ai6CBIgBAAIADgBIAqgQQAJgEADgEQAFgFAGgVIAFgNQAEgGAEgCIABAAIAEgDQADgCAKABQAEAAADgBQAFgFABgNQAEgiAJgQIAHgKIAHgIQAGgEAFgBQAGgDAHABIAEABIAHABIAAAAQADgBABgCIAEgMQADgVAFgRQAIgTALgJQALgJAKABIADAAQAEgBAFABQAKACAMALIAJAHQAGAEADABIAKgDQAHgCAGABIAJAAQAOgBANAMIADACIAHAMQADAGAAAIIAAAIIgCALIgBAKIgBAKQAAAKAEAFIAFAEIADACQAHACACACIABABQADADACAHIAAAEQAAAHgBAHIgCAGQgDAGgEAGQgGAHgJAGIgLAGQgJAGgJADQgIADgJAAQgUACgRgJQgNgGgEgBIgGAAIgBACIgFAJIgCAFQgGALgLAEQgKAIgQgCIgQgFQgMgDgHAAQgIAAgKAEIgTAIQgSAIgWAGQgdAIghAEIgXADIADgBg");
	this.shape_31.setTransform(436.7,45.1);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#444444").s().p("AixB3IgBAAIACgBIAAAAIAlgOQAIgDAEgDQAEgFAGgTIAFgMQADgGAEgCIADgBQADgEADgCQADgCAKABIAEAAQACgFAAgJQAFggAJgOIAFgJIAIgIQAGgFAHAAQAHgEAHACIAEAAIAEABIABgBQABgCACgJQADgUAHgQQAFgRALgJQAKgJALACIADABIAHgCQAFgBAFABQAKACAMAKIAIAGIAEADIACAAQAJgDAJADIAHgBIAJgBQAOgBAMAKIADACQAFAFACAGQACAFAAAHQABACgCAFIgCAKIgBAJIgBAJQABAIADAFIAFADIADACIAHADIABABQAEAEAAAFIAAADIgBAOIgCAFIgHAMQgGAHgJAFQgGADgGACIgDABIgFAEQgIAGgKADQgIADgIAAQgSABgRgIIgOgGIgDAHIgDAEQgHANgNABQgKAMgSgDIgQgEQgLgDgGAAQgIAAgJADIgRAIQgSAIgTAGQgbAHggAEIgVADIAGgCg");
	this.shape_32.setTransform(443.5,45.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#444444").s().p("AixBvIADAAIAHgDIgDABIAAgBIAFAAIAdgLQAIgDADgDQAEgEAFgSIAFgLQADgGAEgBIAFgBQAEgHAFgCQADgCAIAAIABgIQAFgeAIgNIAFgIIAHgHQAIgGAIABIAAABIABgBIACgCQAFgEAIACIACABIADgKQADgSAGgOQAHgQAIgJQAKgIAJACIAHACQAHgEAHgBQAEAAAFABQAKACALAJIAJAGIACACQAFAAAFADQAGgBALgDIAJgBQAOgBAMAIIACACQAFAFACAEQADAFgBAFIgCAIIgCAIIgBAIIgBAIQAAAHADADIAEAEIADABIAHADIABAAQADADABAGIAAADIgDALIgCAFIgHALQgHAHgIAEQgGADgFACIgIACQgEAEgGAEQgIAGgJADQgHACgJABQgQABgPgIIgIgDIgCAEQgJAOgQgCIgCADQgKANgPgDIgQgEQgLgCgGAAQgHAAgJADIgQAHQgQAIgSAFQgZAHgdAEIgRACIgDABg");
	this.shape_33.setTransform(450.2,45.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#444444").s().p("AirBmIADAAIALgEIgEABIAAgBIARgEIAFgCIAEgBIACgBQAHgDADgDQADgEAGgQIAFgKQADgFADgBQACgBAHAAQAEgKAFgDIAGgBIAAgDQAFgcAHgLIAFgJIAHgGQAGgFAHABIAGABIAEgEIABgBQADgDAFABIABgGQADgQAGgOQAHgPAGgHQAJgIAKACQAFABAGADIAAAAIAFgDQAGgEAIgBIAIAAQAKACAMAJIAIAGQAFADAEAAQAGABAOgEIAJgBQAOgBAKAHIACACQAFADACAEQACADgBAFIgBAHIgEAIIgCAGIAAAGQAAAHADACIAEADIACABIAHACIABAAQACADAAAFIAAADIgDAKIgCAEIgIALQgGAGgIAEIgLADIgOADQgFAIgJAGQgHAFgJADIgOACQgQABgOgGIgCgBQgJALgRgGIgDAFIgCAFQgKALgOgCIgPgDQgJgCgGAAQgGAAgIADIgPAHQgPAHgQAFQgYAGgbAEIgPACIgDABg");
	this.shape_34.setTransform(457,45.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#444444").s().p("AikBeIADgBIANgEIgEAAIAAAAIAPgGIASgIQADgEAEgLIAEgJQADgFADgBQACgBAHABIADAAQAEgNAGgEQAEgYAHgLIAFgHIAGgGQAGgEAHABIAIABQADAAACgBIADgGIACgFQADgQAFgMQAGgNAIgIQAHgHAIACQAHABAIAGIAHgFIAEgDQAHgDAHgBQAEAAAEABQAKACALAIIAIAFQAFADAEAAQAGAAAOgDIAIgCQAOgBAKAFIACACQAEADACADQACACgBAFIgDAFIgDAHIgCAFIgBAGQAAAFADACIAEACIACABIAGABIAAAAQADACgBAEIAAADIgEALIgCAEIgIAIQgGAGgIADIgKACIgWACIgBAAIAAADQgFALgLAHQgHAFgHACIgOACQgOABgNgGIAAAAQgHACgKgEIgCgBIgBgBIgDADIgDAFIgCAFIgDAEQgGALgPgCIgOgDQgIgCgGAAQgFAAgIADIgNAGQgOAHgPAFQgVAGgZADIgNACIgDABg");
	this.shape_35.setTransform(463.7,45.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#444444").s().p("AieBVIAEgBIAPgFIgEAAIgBAAIAOgHIAQgHIADgKIAEgIQADgEADgBQACgBAGABQAGAAACgDIAAAAQADgCABgGIAAgEQAEgWAHgKIAEgGIAFgFQAGgEAGAAIAHABQAFABACgEIACgHQADgOAFgMQAFgMAIgGQAHgHAGABQAHABAHAGIAGAFIABgCQAFgGAGgDIAEgDQAHgDAGAAIAJABQAJACALAHIAIAEIAJADQAHAAAMgDIAJgCQANgCAJAFIACABQAFACABACQABACgBAEIgDAEIgDAGIgCAEIgCAEQABAEACACIADABIACABIAFAAIABAAQACABgBAEIgBACIgEAKIgCAFIgIAJQgGADgIACQgFACgFAAIgUABIgDAAIgKABIgBAGIAAAEQgFAKgKAGQgGAFgHACQgGACgGAAQgNABgMgGIgLgEQgHgBgDAFIgBAEIgCAEIgCAEQgIAKgOgBIgMgDIgNgCQgFAAgHADIgMAGQgLAFgNAEIgDACIgDABQgFADgIAAIgHABIgRADIgLACIgEABg");
	this.shape_36.setTransform(470.4,45.5);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#444444").s().p("AiYBMIAGgBIAQgFIgFgBIAAAAIAMgIIAMgHIACgEIADgHQADgDADgBQABgBAGABQAFAAACgCQADgDABgIQAEgUAGgIIAEgGIAEgFQAFgDAGAAIAGABQAEAAACgDIADgGQACgNAFgKQAFgLAHgGQAGgGAHABQAGABAFAFQAHAGADAAIAGgBIADgEQAEgGAGgDIAFgCQAGgCAGAAIAIAAQAKACAKAHIAIAEQAFACAEAAQAHAAAMgDIAIgCQANgCAJADIACABIAFADQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBABIgDADIgEAFIgCADIgBADQAAABAAAAQAAABAAAAQAAABABAAQAAABABAAIADABIABAAIAFAAIAAgBQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAABIgBACIgFAJIgCAEIgJAJQgFAEgIACQgFABgFgBQgJgBgKABIgDABQgNADgKgBIABAEIgBAIIgBADQgEAJgJAGQgFAEgGACIgMACQgMAAgKgEIgJgEQgGgBgDAEIgCAEIgCAEIgCADQgHAJgMgBIgLgCIgMgCQgEAAgGADIgLAFIgLAFQgCAEgFADIgDAAQgFAEgIgBIgNAAIgOADIgHACIgGABg");
	this.shape_37.setTransform(477.2,45.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#444444").s().p("AiTBCIAMgCIAGgBIAGgCIgFgBIAAgCIALgIIAJgGIACgFQADgDACAAIAFAAIAIgEIACgBIABgHQAEgRAFgHIAEgFIAEgEQAFgEAEABIAGABQAEAAACgCIACgHQACgLAEgJQAFgJAGgGQAGgFAGABQAFAAAGAFQAFAFACgBIALgCQAEgCAFABIABgCQAFgGAGgCIAEgCQAGgCAHAAIAHABQAJACALAGIAIADQAFACAEAAQAGAAAMgDIAIgCQAMgCAJABIABABIAFABQAAAAAAAAQAAABAAAAQAAAAAAAAQgBABAAAAIgEAEIgEADIgCACIgCACQAAAAAAAAQAAABAAAAQABAAAAAAQAAAAABAAIACABIACAAIAEgBIAAAAQAAAAABAAQAAAAAAAAQAAAAAAABQgBAAAAABIgBABIgFAJIgDADIgJAIQgFAFgIAAQgEABgFgBQgJgCgJABIgDAAQgQAFgKgBQgIAAgCACIAAAAIgDADIABABQADADAAAEIgBAHIAAADQgEAHgIAGQgFADgFACIgLABQgLABgHgEIgJgEQgFgBgDAEIgCAEIgCADIgBADQgHAIgLgBIgKgCQgGgBgEAAIgKADIgJAEIgBADQgCAGgGADIgCABQgFADgIgBIgQgBIgHACIgSAFg");
	this.shape_38.setTransform(484.1,45.7);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#444444").s().p("AiOA5IAKgCIAQgEIgEgBIAAgCIAJgJQAMgLANgHQADgNAEgIIAEgCIADgEQAEgDAEABIAFABQADAAACgCIACgGQACgJAEgIQAEgJAFgFQAGgEAFAAQAEAAAGAEQAFAEADAAIAIgDQAHgDAHAGIAEAEIACgDQABgEADgDQAEgFAGgCIAFgCQAFgCAHABIAHABQAJACAKAFIAIADQAFACAEgBQAGAAALgDIAIgCQAMgCAIAAIACAAIACAAIgEADIgEACIgDABIACAAIABAAIACgBIABgBIABAAIgBABIgBAAIAAAAIgGAIIgDADIgJAIQgFAEgIAAQgEAAgEgBQgJgDgJABIgDAAQgPAFgKAAQgHABgBADIAAAAQgDABgBAGQAAADgDAFQAAAAAAABQgBAAAAAAQgBABAAAAQAAAAgBAAIgEACIAAAAIgBAFIgBACQgDAHgHAEIgJAFIgJABQgIABgIgEQgGgDgCAAQgFgBgCADIgCADIgCADIgBADQgGAHgKgBIgIgBQgGgBgDAAIgGACIgCAEIAAADQgDAGgFADIgCABQgEAEgJgCQgJAAgHgCIgEABIgWAGg");
	this.shape_39.setTransform(490.9,45.8);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#444444").s().p("Ah/AxIAJgDIASgEIgDACIgFACIgTAEgAhTAvQgKgCgHgDIAAAAIAAAAIgCgCIAAgBIAHgKQAKgLAKgHIAEgIIADgDIACgCQAEgCAEAAIAEABQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAgBIACgEIAFgPQADgIAFgEQAFgEAEAAQAEAAAEADQAFADACAAIAIgDQAFgCAGAEQAEAEABAFIAAAAIAFAGIACABIgFADIgCACIgBABIABADIADABIABABIACABQACACAAAEIgBADIAAACQgEAFgFAEIgIAEIgHABQgIABgIgDIgGgDQgEAAgCACIgCADIgBACIgBACQgGAGgIAAIgHgBIgDAAIgBAFIgBADQgCAGgEADIgDABQgCACgFAAIgFAAgAAVgSIgBgBQAEgEADgFIAEgGIADgGQAEgGAHgBIAEgBQAFgCAGABIAIABIASAGIAFACIgHAAIgDAAIgXAHQgIACAAADIAAAAQgCABAAAGQAAADgEAFIgDABQgCACgDAAQgGAAgJgIgABtgjQgFAAgEgCIgDgCIAGABQAHAAAKgEIAIgBIAAAAIgHAFQgEADgFAAIgDAAgABegnIgDgBIAGABIgDAAgACAgsIAAABIAAgBg");
	this.shape_40.setTransform(496.8,45.9);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#444444").s().p("AiHAzIAIgCIARgFQgDAFgCAAIgEABIgPADgAhZAyQgMgCgGgGIgBABIgCABIAAgBIACgDIABgBIAFgKQAKgOAMgIIAOgHIADgFQADgGAEgEQAEgEADAAQADAAAEACQADADADgBIAGgDQAEgCAEACIACgCIAEgEQAFgGADAAQAHgBAEAJIADADIAJAIIAAAAQgFAIgIADIgCAAQgCACgDgBQgDAAgFgBIgDgCIAAgBQAAABAAAAQAAABAAABQAAAAAAAAQABAAAAAAIACAAIACABIABAAIABAFIgBAEIAAACQgEAEgEADIgHADIgIABQgHABgFgDIgGgCQgEAAgBACIgCACIgBACIgBACQgDADgFACIgBAEIgBADQgBAGgFADIgBABQgCACgFAAIgFgBgAAPgLIADgFIADgGQAEgFAIgBIAAAAQABgDAFgBIAXgJIACAAQAHgBAJAFQADACAFABQAGABAFgDIAKgGIADgDIAHgGIACAAQABgBAAABQAAAAABAAQAAAAAAABQAAAAAAABIAAABIgCADIgBABIgCABIAAAEIACACIADABIAFAAIAFgBQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABQAAAAAAABQAAAAgBAAQAAABgBAAQgBABAAAAIgBAAIgTAGIgHACQgKADgHABIgJgBIgIgCIgSgFIgHgCQgGgBgFABIgDABIAAABQgCADABAFQAAADgEAEIgCACIgEABQgDAAgEgCg");
	this.shape_41.setTransform(504.9,44.8);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#444444").s().p("AiDAyIAGgCIAPgFIAJgGIAEgKQAIgPALgJQAVgKAIAAQADgBAHABQAHgCABgBQADgCAEgHIAEgEIAEgGQAEgGACAAQAGgBAFAKIACACQAMAOAHgCIADgBQAEgEgBgDQgBgGAAgCIAAAAQAAgEAGgDIAVgKIACgBQAHgBAIAGQAEADADABQAHADAFgDIAKgGIADgCQAFgEADgBIACAAQABAAAAAAQABAAAAAAQAAABAAABQAAAAAAABIAAACIgBADIAAABIgBACIAAAGIABADIADADIAGAAIAFAAQADABABADQAAADgDADIgCAAQgFAEgMADIgHACIgQAEIgJAAIgHgCIgSgFIgHgBQgGgBgFAAIgDABQgIAAgDAFIgEAFIgDADQgFAIgIACIgBABQgDACgEgCQgDgBgDgDIgEgBIgBgDQgBgDAHgCIAFgCQABAAABgBQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgFgOAAIgFABIgLAFIgEACIAAAAIABABQABAAABABQAAAAAAABQABAAAAAAQAAAAAAAAIgBAEQAAAAABABQAAABAAAAQAAAAAAABQAAAAAAAAIADABIAAAAQABAAAAAAIABAEIgBADIgBABIgGAGIgGACIgHABQgFAAgFgBIgCgBIgDANIAAADQgCAHgEADIgBAAQgEAEgIgDQgJgDgGgFIAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAIgEABIgCAAIgCADQgDADgCAAIgDABIgMABg");
	this.shape_42.setTransform(511.9,44.1);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#444444").s().p("Ah+AyIgBgCIAEgCIALgEIAHgFIAEgCIADgCIAEgBIACgJQAHgPAJgIQAUgMAIAAIAKAAQAGAAACgCQACgCAEgHIADgEIAEgGIAFgIQAGgBAGAKIAAADQALAQAHgCQAAABAAAAQABAAAAgBQABAAAAAAQAAAAABAAQADgEAAgDIgCgIQgBgFAFgEIAUgLIACAAQAHgBAHAHQADADAEABQAGADAFgCIALgEIADgDQAFgDADgCIADABQACABABAEIAAACIgBAEIAAABIgBADIAAAIIACAEQACACACABIAGACIAFABQAEABABAEQAAAFgDACIgBABQgFAEgMADIgHACIgPAEIgJAAIgHgBIgSgEIgGgCIgLgBIgDAAQgIAAgEAEIgDAFIgDAEQgEAIgJACIgBABQgEAAgDgCIgHgEIgDgCIgBgDQAAgDAIgEIAHgFQAEgCAAAAQAAgGgOgCIgGABIgLADIgEABIgGADIgHADIgFAIIABABIgBABQAAABAAAAQAAAAAAAAQAAABAAAAQABAAAAgBIABABIABAAIAAADIgBACIAAAAIgFAEIgDACIgCAKIAAADQgCAHgDACIgBABQgEAEgIgEQgLgDgFgJIAAAAIAAAAQgDADgCAFIgCACQgBABAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAIgCAAIgDgBIgBACQgBABAAAAQgBABAAAAQgBAAAAAAQAAAAgBAAIgCABIgJgCg");
	this.shape_43.setTransform(518.8,43.5);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#444444").s().p("AhyA2IgCgBIgGgCIgBgCIADgDIAGgDIAFgFIACgCIACgBIACAAIADgBIAGgEIAAAAIAAgBIABAAIACAAIACAAIABAAIABgHQAGgRAIgHQATgNAHABIAJAAQAHgBABgBQACgBAFgJIACgEIADgGIAFgIQAEgCAHALIACADQAIAQAGABQABAAAAAAQABAAAAAAQAAAAABAAQAAgBAAAAQAEgDgBgDIgEgJIABAAQgCgEAFgFQAFgGANgHIACAAQAGgBAHAHIAHAGQAGAEAFgBIAKgFIAEgCQAFgEAEAAIACABQAEACAAAFIAAABIABAFIgBACIAAADIABAJIABAGQACADACACIAGACIAGACQAFACAAAEQABAEgDAEIgBAAQgEAHgMAEIgGACIgPAEIgJABIgHgBIgRgDIgGgBIgKgDIgEAAQgHAAgEAEIgDAEIgDAEQgFAHgIABIgCAAQgEAAgEgCIgGgFIgCgCIgBgDQABgEAIgFIAJgGQADgDgBgCQABgHgNgCIgGgBQgHAAgFACIgEACIgFABQgEACgDADQgFAGgDAJQgDAIgBAIIAAADQgCAIgCACIgBABQgDAEgJgEQgJgEgEgIIgBABIgDAFIgBABIgBAAIgCAAIgCABIgBAAIgBABIgFAFIgBABIgCAAIgBAAIgCgBIgCABIgBAAIgBAAg");
	this.shape_44.setTransform(525.8,42.6);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#444444").s().p("AkwCcQgOgIgFgRQgBgDADgEIAFgHQAMgaAPgFQAHgCAVABIALgBQAGgCAAACQACA/gjAMQgGACgFAAQgIAAgIgFgAi9CLQgegQgGggQgCgOADgYQALgxATgWQAMgRASgJQATgKATACIAZADQAOABAGgIQADgDASgkQARgjABgFQAEgRAcA0QAdA8ASgKQALgGgFgLQgIgNgDgJQgNghBBgjQARgJAWAdQAXAgAWgEQAHgBAfgQQAWgLANAIQAJAGACAPIADAaQACAOABAbQADAWANALQAFAFAMADQAOADAFADQALAIADAQQACAPgHANQgLAWghAPQglAQgpACQgqACgmgNQgagIgKgBQgVgDgLALIgHAJIgHAKQgPATgYAAQgfgBgUgeQgHgMAlgXQAogaABgNQACgcgpgIQgogKgVAMQgyAagMBNQgEAfgGAGQgEAFgHAAQgJAAgNgGg");
	this.shape_45.setTransform(532.7,41.9,0.369,0.369);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#444444").s().p("AhJAsIAFgCIACgCQACgCACgGIACgCQACgFADgCIADgBIACAAIAFAAIACgBIAEgBIABAAQACgBABgFIACgEQACgFAAgFQgBgCACgCIABgBQACgEADgDIAEgBQADgCACAAIAFABIABAAIAFgBIABAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIABgGIADgJIADgEQADgFAFgDIACgBQAFgDAFABIACAAQAFABAEAEIACAAIAIAEIAEAAIAGAAIAGgBQAEAAABADQAAADACACIABABQAGAGABAFIAAABIAAAGIAAAEIADAFIADACIAEACIACAAIADABIACAAIACADIABACIABAEIgBAEIgCADQgCAFgHADQgKAFgJAAIgBAAQgKABgJgDIgCgBIgIgCIgBAAQgEgBgCADIgCABIgBACIgBAAIgBACIgBACQgDADgHABIgIAAIgEgBIgEgBIgCAAIgHAAIgBAAIgJABIgCAAIgIAEIgCAAQgcAIgmADg");
	this.shape_46.setTransform(316.1,52.7);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#444444").s().p("AhjA8IAHgCIADgCIAGgLIACgEQACgGAEgDQABgBAAAAQAAAAABAAQAAAAABgBQAAAAABAAIACAAIAHAAIADAAIAGgCIAAgBQADgCABgHIACgGIAEgMIADgIIABgBQADgGAFgDIAFgCQAEgCAEAAIAGABIACAAQADAAADgBIABgBQACgBABgFIABgKQACgGADgEIADgGQAFgHAGgDIADgCQAHgDAHABIADAAQAGACAGAFIACABQAHAEAEABIAHAAIAHgBQAFgBAFAAQAEAAADADQACADADACIABACQAIAHABAIIAAAAIAAAJIAAAHQAAAFACAEIACADIAHADIACABIAEABIACAAIADAFIABADIAAAGIgBAEIgCAFQgFAGgIAFQgMAGgOABIgBAAQgNAAgMgEIgCgBIgMgDIgBAAQgGgBgEAEIgBABIgBADIgCABIgBACIgCADQgEAFgJABIgKAAIgGgBIgGgBIgDgBIgKgBIgBAAQgFAAgIACIgCABIgLAEIgDAAQgmANgzACg");
	this.shape_47.setTransform(324.7,46.6);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#444444").s().p("Ah3BKIAIgDIADgCQAEgEAEgKIACgEQADgJAFgDIADgCIAEAAIAIAAIADgBIAHgCIABgBQADgDABgIIACgIIAFgQQACgFACgDIACgCQAEgHAGgEIAHgDQAEgBAFAAIAHABIADAAQAEABADgCIABgCQACgBABgGIACgNIAFgMIAFgHQAFgIAHgEIAEgCQAIgEAJABIAEABQAHACAHAGIADABQAIAFAFABQACABAGgBIAJgBQAGgCAGABQAFAAAFADIAHAGIACABQAJAJABAJIAAABIgBALIAAAJQgBAHACAFIADAEIAIAEIACAAIAFACIACABIADAFIABAEIAAAIIgBAFIgDAGQgFAHgKAFQgPAHgQACIgBAAQgQAAgOgFIgDgBIgOgEIgBAAQgIgBgEAFIgCACIgBACIgCADIgBACIgDADQgGAGgKACIgMAAIgGgBIgIgCIgEgBIgLgBIgCAAQgHAAgJACIgCABIgOAFIgDAAQguAQg9ADg");
	this.shape_48.setTransform(331.4,41.8);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#444444").s().p("AiGBTIAJgDIAEgCQAEgEAFgMIACgEQADgKAFgEIAEgCIAEgBIAJAAIAEAAQAFAAADgCIAAgBQAEgEABgKIACgIIAGgTQACgFADgEIACgCQAFgIAHgFIAHgCQAFgCAFABIAJABIACAAQAFAAAEgCIABgCIADgJIACgOIAGgOIAGgHQAGgJAHgFIAFgCQAJgEAJABIAFABQAHADAJAGIACABQAKAGAFABQADABAHgBIAKgBQAHgCAGABQAGAAAGADIAJAGIACACQAJAJACALIAAABIgBAMIgBAKQgBAIACAGIADAFQADACAGACIADABIAFACIADACIADAGIABAEQAAAEgBAFIgBAGIgEAGQgFAIgLAFQgRAJgRABIgCAAQgRABgQgGIgEgBIgQgFIgBAAQgJgBgFAGIgBACIgCADIgCACIgBADIgDAEQgHAHgLABQgGABgHgBIgHgBIgKgCIgEgBIgMgBIgCAAQgIAAgKACIgDABIgPAFIgEABQgzARhFAEg");
	this.shape_49.setTransform(336.2,38.3);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#444444").s().p("Ai+BnIAwgOIAIgDIAFgDQAEgEAFgMIACgFQAEgKAFgEIAEgDIAEAAIAKAAIAEAAQAFgBADgCIABgBQAEgFABgKIACgJQADgMAEgIQACgGADgEIACgCQAFgIAIgFIAIgDQAFgCAGABIAIABIADAAQAGABADgDIACgCIADgJIACgPQADgJAEgHIAFgIQAHgIAIgGIAFgCQAJgFAKACIAFABQAIADAKAGIACACQAKAGAGABQADABAHgBIALgCQAIgBAGAAQAHABAGADIAKAGIACACQAKAJACAMIAAABIgBAOIgBAKQgBAJACAGQABAEACACIAJAFIADABIAFABIADADIADAGIABAEQABAFgBAFIgCAGIgEAHQgGAIgLAGQgSAJgTABIgBAAQgTABgQgGIgEgBIgSgFIgBAAQgJgCgGAGIgBADIgCADIgCADIgBACIgEAFQgHAHgLACQgHABgIgBIgHgBIgKgDIgFAAIgNgCIgCAAQgIAAgLADIgDABIgQAFIgEABQg2AShJAEg");
	this.shape_50.setTransform(339.1,36.2);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#444444").s().p("Ai+BmIgBAAIAigKIADgBIAKgDQAKgDADgDQAEgEAHgQQAGgOAHgDIADgCQADgBAKABQAGAAAEgBIAAgBQAEgEACgLQAFgaAJgMQAGgKAIgFIAJgEIAGgBIAHAAIAHABIAFAAIADAAIADgCQACgCACgIQADgQAFgOQAJgOALgIQAJgFAJgBQAGgBAFABQALACAMAJIAIAEQAGAEAEABIACAAIANgCQAHgCAGABIAEAAQAOgBAOAJQAIAHADAIIACAIIAAAGIgCAKIgBAIIAAAFQgBAKAFAFIAFADIADACQAHACACABQAEABABAFIACAFQAAAFgBAFIgBAFIgEAGQgFAHgIAFIgFADIgGADQgSAJgUABQgUABgSgHIgSgGQgFgBgFACIgBABIgDAGIgEAFQgCAEgDADIgIAFIgFACQgJAEgNgCIgRgDQgMgDgHAAQgIAAgLADIgTAGQgXAIgZAGQgcAFgfADIgWABg");
	this.shape_51.setTransform(346.2,36);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#444444").s().p("Ai4BhIgCAAIAKgCIAigKQAJgDADgDQAFgEAGgPQAGgOAHgCIAAgBIAFgCQADgCAKABIAIgCQADgEABgIQAFgaAJgLQAGgKAIgFQAEgCAFgBIAJgDIAHAAIAGABIAFABIABAAIACgCIADgJQADgQAFgNQAIgOALgHQAJgGAKABIABAAQAHgCAHABQAKACANAIIAHAFQAGADAFABIAHgCQAIgCAIABIAIgBQAOAAANAIQAIAHADAHQACAEAAAEIAAAGIgCAJIgBAHIgBAFQgBAKAFAEIAFADIADABIAIADQAEADABADIACAFQAAAEgBAEIgBAGIgEAFQgFAHgIAFIgFADIgNAFQgRAJgTABQgTABgSgHIgRgFIgHAAIgCAEIgDAGIgFAGQgFAEgGACIgHAEQgIADgNgBIgQgDQgMgDgHAAQgIAAgKADIgSAGQgWAIgZAFQgaAFgfADIgVABg");
	this.shape_52.setTransform(352.3,36.5);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#444444").s().p("AizBdIABgBIgDABIAKgDIAegIQAKgDADgCQAEgEAGgPQAFgOAHgCIADgBIAEgDQAEgCAJAAIAGAAQADgEABgHQAEgZAJgKQAFgJAJgFQAEgDAGgBIACgBQAEgCAFgBIAGABIAGABIADAAIABAAQABgCABgHQAEgPAGgMQAHgOAKgHQALgGALABIACgBQAIgBAGABQAKABANAIIAHAFIAHADIAEgBQAIgCAJACIADgBIAKgBQAOAAANAHQAIAGADAHIACAHIgBAGIgCAJIgCAGIAAAFQgBAJAFAEIAEACIADACIAIADQADADACADIACADIgBAIIgBAFIgEAGQgFAFgIAFIgGADIgMAGIgDABIgDACQgQAIgUABQgRABgSgHIgQgEIgEgBIAAACIgDAFIgGAGQgEAFgHACIgCABQgDADgEABQgJAEgMgCIgPgDQgMgCgGAAQgIAAgKADIgRAGQgVAHgYAFQgaAFgdADIgVACg");
	this.shape_53.setTransform(358.4,37);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#444444").s().p("AiwBZIAEgBIgFAAIAIgBIAegIQAJgDACgCQAEgEAGgOQAGgNAGgCIADgBQAEgEADgBQADgCAJAAIAFAAIACgIQAEgYAIgKQAGgJAIgEQAFgDAGgBIABgBIADgCIAJgCIAGAAIAGACIACgIQAEgOAGgMQAFgNALgHQAKgGAKABIADABIAFgCQAHgCAIABQAKACALAIIAHAEIAGADQAJgCAJACIAIgCIAKgBQAOgBAMAHQAHAGAEAGIABAHIgBAFIgCAIIgCAHIgBAEQAAAJAEADIAEACIADACIAIACQAEADABADIABADIgBAHIgBAFIgEAFQgEAFgJAFIgFADIgMAGIgGABIgGAEQgRAIgRABQgTABgQgGQgLgEgFgBIAAAAIgCADIgFAHQgEAEgGACIgGADQgEADgEACQgJADgKgBIgQgDQgLgCgGAAQgIAAgJACIgRAGQgVAHgWAFQgZAFgcADIgTACg");
	this.shape_54.setTransform(364.6,37.5);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#444444").s().p("AitBVIAIgCIACAAIAZgHQAJgDADgCQADgEAGgNQAFgMAGgCIAGgBQADgFAEgCQADgCAIAAIADAAIABgGQAEgXAIgJQAFgIAIgFQAGgDAFgBIACAAIAEgCIADgCQAEgCAEAAIAFABIADABIABgFQADgOAGgMQAHgMAIgHQAKgGALABIAFACIAIgDQAHgCAHABQAKACAMAHIAHAEIADACQAHAAAHACIAOgDIAJgBQAOgBAMAGQAHAGADAFIABAGIAAAFIgDAIIgBAGIgBAEQgBAIADADIAFACIADACIAHACQADACABADIABAEIAAAFIgCAEIgDAFQgFAFgIAFIgFADIgNAFIgIACIgKAHQgPAIgSAAQgRABgQgGIgMgEIgEAGQgEAEgGADQgDACgGAAIAAAAQgEAGgHACQgIADgIgBIgRgDQgKgDgGABQgHAAgKACIgQAGQgTAHgWAFQgYAEgaADIgTACg");
	this.shape_55.setTransform(370.7,38);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#444444").s().p("AiqBSIAKgDIgHABIARgEIAXgHIACgBQADgDAGgNQAFgLAGgCIAHgBQADgGAFgCQADgCAIAAIAAgEQAFgWAHgJQAFgIAHgEQAGgDAFAAIADAAIAIgFIADgBQADgCAEAAIADAAIABgCQADgNAGgLQAHgMAHgGQAKgGAKABIAIACIACgBIAJgDQAHgCAHABQAKACALAHIAHAEQAGADAEAAQAGABAPgDIAJgCQANgBANAGQAGAFADAFIABAFIgBAFIgCAHIgCAGIgBAEQgBAHADADIAEACIADABIAHABQADACABAEIABADIAAAFIgCADIgDAEQgFAFgIAFIgFADIgMAFIgNADQgFAFgHAEQgPAHgRABQgQABgPgGIgKgDIgBACQgEAEgFADQgDACgFAAIgFAAIAAAAQgEAHgHADQgIADgIgBIgQgDIgQgCQgHAAgIACIgQAGQgSAHgVAEQgXAFgaADIgRABg");
	this.shape_56.setTransform(376.8,38.5);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#444444").s().p("AinBOIANgDIgJABIARgGIAYgHIAGgNQAFgLAGgBQADgCAGABQAEgIAEgDQADgBAFgBIAAgBQAEgUAIgJQAEgHAHgFQAGgDAFAAIAEABIACAAIAAAAQAEgFAFgDIADgBIAGgBQACgMAGgLQAHgMAHgFQAJgGAKABQAEABAGACIAGgDQAEgDAEAAQAHgBAHABQAKABALAHIAHAEQAGACAEAAQAGACAOgEIAJgBQAOgBALAEQAHAFACAFIABAFIgBADIgCAIIgCAFIgBAEQgBAHADACIAEABIACABIAHABQADACABADIABADQAAADgBADIgBADIgEADIgNAJIgEADIgNAFQgIACgIAAIgCABQgFAGgIAFQgOAHgQABQgQAAgOgFIgHgCIgGAFQgDACgFAAIgIAAIgBAAIgBADQgFAGgGADQgGACgKAAIgPgDQgJgCgGAAQgGABgJACIgPAGQgRAFgUAFIguAHIgRACg");
	this.shape_57.setTransform(382.9,39);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#444444").s().p("AikBKIAPgDIgJAAIAQgFIAWgIIAFgKQAFgKAGgCQACgBAHABIABAAQAEgJAFgDIAFgCQAEgTAHgIQAEgHAHgEQAFgCAFgBIAEABIADAAIAEgDQAEgFAFgCIACAAIABAAQACgMAGgKQAGgKAJgGQAHgGAJABQAFABAHAEQAEgEAGgCQAEgCAEAAQAHgBAHABQAJABALAHIAHADQAGADAEAAQAGABAOgEIAJgBQANgBAMAEQAGAEACAEIABAFIgBADIgDAHIgCAEIgBAEQgBAHADABIADABIADABIAGABQADABABADIABADQAAADgBACIgBADIgEAEIgNAHIgEACIgNAGQgKADgLgCIAAABIgEAFQgEAGgIAEQgOAHgPAAQgPABgOgFIgEgCIgCACQgDACgFAAIgIAAIgEgBIgBACIgDAEQgEAGgFADQgGACgKAAIgOgDQgJgCgGABQgGAAgIACIgOAFQgRAGgTAFIgsAHIgQACg");
	this.shape_58.setTransform(389,39.5);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#444444").s().p("AigBHIAPgEIgIAAIAOgFIAWgJIADgHQAFgKAFgBQADgBAGABIABAAIACAAQAFgKAFgEIABgBQAEgRAHgHQAEgGAHgEQAEgDAFAAIADABIAGAAIAHgHIAGgEQACgKAFgJQAHgLAIgEQAGgGAJAAQAHABAHAFIAEgCQAEgDAGgCQAEgCAEAAQAHgBAGABQAJABALAGIAHADQAGADAEAAQAGAAANgDIAJgBQANgCALAEQAHAEACADIABAEIgBAEIgDAFIgDAFIgBADQgBAHACAAIAEABIACABIAGABQABAAAAABQABAAAAAAQABABAAAAQAAAAABABIAAACIAAAGIgBACIgEADIgNAGIgEADIgNAGQgKACgLgCIgGAAIgBAFIgDAFQgFAFgIAEQgNAHgPAAQgOABgNgEIgDgCIgEABIgHAAIgHgBIgCABIgDAEIgCADQgEAGgEACQgHADgJgBIgNgCQgJgBgGgBIgMADIgOAFQgRAGgSAEQgTAEgWADIgQACg");
	this.shape_59.setTransform(395.2,40);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#444444").s().p("AieBDIASgEIgJAAIAPgGIATgJIABgEQAFgJAFgBQACgBAHABIAAAAIAGAAQADgKAFgEQADgQAHgGQADgHAHgDQAEgDAFAAIADAAIAGABIADgCQAEgFAEgCIAAAAQADgLAEgIQAGgKAIgFQAIgGAGABQAHABAIAFIADABIAHgFQADgDAGgBIAIgDQAHAAAGABQAJABALAGIAHADQAFACAFAAQAGABANgDIAJgCQANgBAKACQAHADABAEIABADIgCADIgCAFIgDAFIgBADQgBAFACABIADABIACABIAGgBQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAIABACIAAAEIgCADIgEACIgNAIIgEACIgMAEQgKADgLgCIgJgCIgEgBIAAACQAAAFgCAFIgDAEQgEAFgHAEQgNAGgOABQgNABgMgFIgNgDQgGgBgEAEIgDADIAAAEQgEAFgFACQgGADgKgBIgMgCIgOgBQgFAAgHACIgNAFQgPAGgRAEQgFADgJAAIgBAAIgZADIgOACg");
	this.shape_60.setTransform(401.3,40.4);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#444444").s().p("AibA/IAUgEIgJgBQAGgCAHgEIASgIIAAgCQAEgIAFgBQACgBAHAAIAAAAQAGABACgCIABAAQACgCABgGIAAgBQAEgRAGgGQAEgGAGgDQAEgDAEAAIADAAIAIABIAAAAIAGgGIADgCIAAAAQACgLAFgIQAFgJAIgFQAHgFAIAAQAFABAHAFIAHADQAEgFAFgDQAEgDAGgBIAIgCQAGgBAHABQAJACAKAFIAHADQAFACAFAAQAGABANgDIAIgCQANgCALACQAFADACADIABADIgCACIgDAFIgCAEIgCADQgCAFADAAIACABIADAAIAFAAQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAIABACIgBADIgBACIgEACIgNAIIgEADIgMAEQgKACgLgCIgIgBIgYgHIgDAAIAAAAIAGADIAFACIADADIABADQAAAFgCAEIgDAEQgEAFgGAEQgMAGgOAAQgNABgMgEIgLgEQgGgBgCAEIgCADIgCAEQgEAFgFACQgGACgJAAIgMgCQgIgCgEABQgFAAgHACIgMAEIgWAIIgFADQgGADgIgBIgHABIgUADIgOABg");
	this.shape_61.setTransform(407.4,40.9);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#444444").s().p("AiYA7IAVgEIgJgBIANgHIAQgJQAEgGADgBIAIAAIABAAIAJgDIADgHQADgPAGgGQADgGAGgDQAEgCAFAAIACAAIAHABIADAAIAFgGIABgCQACgKAEgIQAGgJAHgEQAHgFAHAAQAFABAHAEQAGAFAEAAIACAAIAAgBQAEgGAGgDQAEgCAFgCIAIgCQAHAAAGABQAJABALAFIAGADQAFACAFAAQAGAAANgDIAIgBQAMgCAKABQAHACABADIABACIgCACIgEAFIgDADIgBADQgBABAAABQAAABAAAAQAAABABAAQAAAAAAAAIADAAIACABIAFgBQABAAAAAAQAAABABAAQAAAAAAAAQAAAAAAABIABABIgBADIgBACIgDACIgNAHIgEACIgMAGQgKACgLgDIgIgCQgKgEgMgDIgNAAQAAAEACACIAFADIAFABIADAEIABABQAAAFgCAEIgDAEQgDAFgHADQgLAGgNAAQgMABgMgEIgKgDQgEgBgEAEIgBADIgCADQgEAEgFACQgGADgIgBIgLgBIgMgCIgLADIgMAEIgNAFQgDAEgFACQgGADgIgBIgKAAIgTADIgMACg");
	this.shape_62.setTransform(413.6,41.4);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#444444").s().p("AiVA4IAYgFIgKgCQAGgCAGgFIAPgJQACgCADAAIACgBIAJgEIAHgDIABgCQADgOAGgHQADgEAFgDIAIgDIADABIAGAAQAEABACgDIACgFQADgJAEgHQAFgJAGgEQAHgEAHAAQAGAAAFAEQAGAEAEAAQACAAAHgBQAEgGAGgCQAEgDAFgBIAIgCIANABQAIABALAFIAGACQAFACAFAAQAGAAAMgDIAIgBQANgCAKABQAFABACACIAAACIgCACIgEADIgCAEIgCACQAAABgBABQAAAAAAABQAAAAAAAAQABABAAAAIACAAIACAAIAFgBQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIABABIgBACIgBACIgDABIgNAHIgFADIgMAEQgJADgKgDIgIgCQgLgFgLgDQgJAAgEABIgHACQgBAHADADIAFACIAEABIADAEIABABQAAAEgCAEIgDAEQgDAEgGADQgLAFgMAAQgMABgKgEIgIgCQgGgBgDADIgCADIgCADQgDAFgFABQgGACgHAAIgLgCIgLgBIgKADIgLAEIgIADIAAAAQgDAGgGACQgFADgIgCIgMAAIgSADIgMACg");
	this.shape_63.setTransform(419.7,41.9);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#444444").s().p("AiRA0IAWgDIACgBIgJgCIALgIQAPgLAPgHIAGgCQACgMAFgGQADgDAFgCQAEgCADAAIADAAIAGABQADAAACgDIACgEQACgJAFgHQAEgIAHgEQAGgEAGAAQAGAAAGAEQAEAEADAAIALgDIAHgBQAEgFAFgCIAJgDIAIgBQAGAAAGABQAJABAKAFIAGACIAKACQAGAAAMgDIAIgCQAMgCAKAAIAGACIABACIgCABIgFAEIgCACIgCACQAAABgBABQAAAAAAABQAAAAAAAAQAAAAABAAIACAAIACAAIAEgCIACABIABABIgBABIgBACIgEAAIgNAHIgEACIgLAFQgKADgKgEIgHgCQgLgFgLgCIgMAAQgIACgEAFIgDAEIAAAAQAAAFACABIAEACIAFACQAAAAABAAQAAABAAAAQABABAAAAQAAABAAAAIABABQAAAEgCADIgDAEQgDAEgFADQgKAFgMAAQgLABgIgEIgJgCQgGgBgCADIgCADIgCACQgDAEgFACQgFACgHAAIgKgBQgGgCgEABQgFAAgFACIgKAEIgBAAIgCAEQgDAEgFADQgGADgIgBIgOgCIgRADIgMACg");
	this.shape_64.setTransform(425.8,42.4);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#444444").s().p("AiPAxIADgBIgGABgAiIAvIASgDIgIgDIAKgIQAOgLAPgHIADgCQADgHADgFQADgCAFgDIAGgCIADABIAGAAQAAAAABAAQABAAAAAAQABgBAAAAQABAAAAgBIACgEQACgIAEgHQAFgHAGgEQAFgEAHAAQAEAAAGAEQAGADADAAIAIgCQAHgDAHADIAAgBQAEgFAGgDQAEgCAFAAIAIgBIAMABQAJABAJAEIAGACIAKACQAHAAALgDIAIgCIAVgDIAGABIAAABIgCABIgEADIgCADIgCABIgBACIACAAIABAAIAEgCIACAAIABAAIgBABIgBABIgEAAIgNAHIgEACIgLAFQgJACgKgDIgHgDQgLgFgLgCQgHAAgEABQgIABgEAFIgDAEIgCAGIgCAFIgBACIADABIAEABIACADIABACQAAACgCAEIgCADQgDAEgFACQgKAFgLAAQgKABgHgDIgJgDQgFgBgDADIgCADIgBACQgDAEgEACQgFACgHAAIgJgCIgKAAIgJABIgFACIgDAGQgCAFgFADQgFADgJgCIgOgCIgBAAIgFACIgRACIAEgBg");
	this.shape_65.setTransform(432,42.9);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#444444").s().p("AiNAtIADgBIgGACgAiGArIASgDIgGgDIAJgJQANgMAOgHIACgBIAEgGQACgCAFgCQADgCADAAIACAAIAGABQABAAAAAAQABAAAAAAQABgBAAAAQAAgBABAAIACgEQACgHAEgGQAEgHAFgEQAGgEAFAAQAFAAAFADQAFADADAAIAJgCQAHgDAIAEIADACIADgEQAEgGAGgCIAJgCIAHgBIAMABQAJABAJAEIAGACIAKACQAGgBALgDIAIgBIAVgEIAGAAIAAABQAAgBAAAAQgBAAAAAAQAAAAgBABQAAAAgBAAIgEADIgCACIAAAAQgFABgIAEIgEADIgMAFQgIACgKgEIgHgDQgKgGgLgBIgLABQgHACgEAFIgDAEIgDAFIgBAFIgDAIIgBACIABAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAABQABACgCADIgDADQgCADgFADQgJAEgLAAQgHABgIgDIgIgCQgFgBgDADIgBACIgCACQgCAEgEABQgFACgGAAIgJgBIgJgBIgHACIgBACIgDAGQgCAFgFACQgFAEgIgCQgJgBgGgCIgBABIgGABIgQACIAEgBgACFglIACgBIABAAIADAAIgEACIgBgBIgCABgACLgmIAAgBIACgBIAAABIAAAAIgCABg");
	this.shape_66.setTransform(438.2,43.4);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#444444").s().p("AiLAqIACAAIgFABgAiFApIAUgEIgDACIgFACIgQABIAEgBgAhhApQgJgBgHgDIgGgDIAJgKQAMgMANgHIAEgCIAFgDIAGgBIACABIAAAAIAKgDIABgCQACgHADgGQAEgGAFgDQAFgEAFAAQAFAAAFADIACABIAGgCQAEAAACABIACAAQAHgDAFADQAFADABAFIAAAGIADgFIADgGQABgDADgCQAEgGAGgBIAJgCIAHgBIABAAQgHACgEAFIgDAEIgCAFIgCAFIgCAIQgBACgEACIgGAAIgGgBIABACIADABIADABIACACIABACQAAABgCADIgCADQgDADgEACQgIAEgIAAQgJAAgIgCIgHgCQgFgBgCADIgCACIgBACQgCADgEABQgFACgFAAIgIgBIgIAAIgCAAIgBADIgCAGQgCAFgFADQgDACgEAAIgGgBgABWgfIAGAAQAHAAAKgDIAIgCIACAAQAIgFAFgBQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAABIABAAIABgBIAAABIgBAAIgRAFIgEACIgMAFIgFAAQgGAAgGgCgABSggIgFgCQgKgDgIgCIgLgBIALgBQAKABAKAGIAHADIgEgBgACBgkIACgBIABAAIADgDIABgBIABAAIACAAIABAAQABgBAAAAQAAAAABAAQAAAAAAAAQAAAAABABIgEAAIgEACIgCACIgCABIgCABIAAgBgAAwgog");
	this.shape_67.setTransform(444.4,43.7);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#444444").s().p("AiEAqIASgEIABgCIgDgCIAIgKQALgMANgIQAPgFAIgDIADgFQAEgGAFgDQAEgEAFAAQAEAAAEACIAIgEIAJgBQAGAAABACIABACIAAAAIADABQAEACAAAEIAAADIAKADQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBIgDgBIAAABQAAAFAAABIADABIADABIACAAIAAABQAAAEgBACIgDACQgCADgCACQgHADgKABQgIAAgHgCIgHgCQgEgBgCADIgCABIgBACQgCAEgDABQgEABgGAAIgHAAIgCgBIgCAEIgCAGQgCAFgEADQgFACgIgBQgKgCgGgEIgDABIgDADIgFACIgQAAIAGgBgAAPgIIgFAAIADgEIADgGIADgFQAEgFAHgBIAAgBIgCAFIgBAFIgBAIQgBACgEACIgDABIgDgBgABQgYIgGgCQgJgDgIgBIgMgCIgHABIgIABIAAAAIADgEQAEgEAHgDQAEgBAHgBQAKABAJAGIAHADQAJAFAIgCIALgFIAEgCQAJgEAEgBIAEABIABAAIABABIgBABIgBABIgDADIgBAAIgBACQAAABAAAAQAAAAAAAAQAAAAABAAQAAAAABgBIACAAIACgCIAFgBQABgBAAAAQABAAAAAAQAAAAAAABQABAAAAAAIAAAAQAAACgFAAIgUAGIgHACQgLACgGABIgKgBg");
	this.shape_68.setTransform(450.8,43.8);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#444444").s().p("AhcAsQgJgCgHgFIgCABIgCABIAAgBIACgCIgCgCIAIgKQAKgNAMgIQAPgFAIgDIAGgFQAEgDAEAAQADgBAEACIABAAIAAAAQAHgHAJgBIAJgCQAFABACADIAAABIAAACIgIgCQgIgDgGAEQgBAEgDACIAHgDQAGgCAGADQAEACABADIgBAFQgBACACABIACABIADAAIACACIAAABQAAABAAAAQAAABAAABQgBAAAAABQAAAAgBABIgCACIgGAEQgGADgJABQgHAAgHgCIgGgBQgEgBgBACIgCACIgBABQgCADgDABQgEACgFAAIgCAAIgBADIgDAFQgCAGgDACQgDACgEAAIgHgBgAiHAsIABAAIgDABgAiGAsIAAAAgAiCArIASgEQgCADgCABIgFABIgNAAIAEgBgAAIAAIgFgCIgEgDIgDgDIgCgCQgBgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIABgBIAAAAIAFADQAKADAFABIAAAAIgCADQgDAFgCAAIAAAAgAAPgIIACgDQABgDADgCQACgDADgCIAAAAIABgFIACgFIADgEQAEgEAGgCIALgDQAKABAJAGIAGADQAJAFAIgCIALgEIAEgDQAJgEAEAAIAEABIABABIAAABIAAABIgBACIgCAEIgCAAIgBACQAAAAAAABQAAAAABAAQAAABAAAAQABgBABAAIACAAIACgBIAGgBQAAAAAAAAQABAAAAAAQABAAAAAAQAAAAAAAAIABABQgBACgEABQgIADgMADIgHACIgQAEIgJgBIgHgCQgJgDgIgBIgLgBIgHAAIgJABIgEABIAAAIQAAADgFACIgDAAIgDAAg");
	this.shape_69.setTransform(456.9,43.8);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#444444").s().p("AhZAtQgKgDgGgFIgBAAIAAAAIgCgDIAGgKQAKgOALgIQAWgKAIAAIALAAIACAAIgFAFIAEABIAHgDQAFgCAFACQAEABAAADIAAACQAAABAAABQAAAAAAABQAAAAAAABQAAAAABAAIACABIACAAIACABIAAACIgCAEIgCACQgBACgEABQgGADgIAAQgHABgGgCIgFgBQgEgBgBACIgCABIgBACQgBACgDABIgDABIgBAEIgCAFQgCAGgEACQgCACgEAAIgHgBgAiFAtIAFgCIARgEQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAIABAAIgFACIgBABQgCAEgCAAIgEABIgNAAgAiFAtIAAAAIgCAAgAiFAtgAAHAEQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBgBAAIgEgCIgDgDIgCgCQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAABgBIACgDIAAgCIgBgBIAEACQAJADAFABIAGAAIABgBIgBABQgCACgBADIgEAEQgDAEgCAAIgBAAgABPgIIgFgCIgRgEIgLgBIgHAAIgJABQgEAAgDACIABgCIAAgIIABgFIACgFIADgEQAEgEAGgCIAKgDQAKAAAJAHIAFADQAJAFAIgCIALgEIAEgCQAIgFAFAAIADACIABABIABACIAAABIgBADIgCAEIgBABIgBABQAAABAAABQAAAAABAAQAAABAAAAQABAAABAAIACAAIADgBIAFgBIADABIABACQgBACgEABQgIAEgLAEIgHACIgRADIgJAAgAgjgLQADgDAFgBIAAgCQAGgEAIADIgGAAIgIADQgCADgDABIgGADIADgDgAgFgQIgIgCIAAAAIADAAQAEABACACIgBgBg");
	this.shape_70.setTransform(463.1,43.8);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#444444").s().p("AhWAuQgHgCgFgEIAAAAIgGAAIAAAAIgDAAQgDAAgDACQAAABAAABQgBABAAAAQAAABgBAAQAAAAgBAAIgDABIgMgBIgCAAIAHgCIAOgEIAJgEIgBgCIAFgLQAJgOALgIQAVgKAIAAIAKAAQAHgBACgCQADgBACgFQAEgEAJACIAHADIAGADQAIAEAFAAQADABADgBQAEgCAAgDIAAgIIAAgFQAAgCACgDIACgEQAEgEAGgCIAKgEQAKAAAIAHIAGAEQAIAFAIgBIALgFIADgCQAIgFAGABIADACIABACIABACIgBABIAAAEIgCAFIgBAAIAAACQAAABAAABQAAAAABABQAAAAAAABQABAAAAAAIADAAIADgBIAFAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABIABACQgBACgEACQgHAFgMADIgGACQgKADgGAAIgJAAIgGgBIgRgDIgLgCIgHAAQgEgBgEABQgGABgEAFQgCABgBABIgEAFQgDAFgDgBIgEgCIgDgFIgEgCIgCgBQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAgBQABAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBIAAgCQgBgDgFgCIgJAAQgLABgGAFIgDADIgGAFIgHADIgBABIAFAAIAFgCQAFgBAEAAQABABABAAQAAAAABABQAAAAABAAQAAABAAAAIAAADQgBABAAABQAAAAABABQAAAAAAAAQAAABABAAIABAAIACAAIABABIAAABIgBADIgCACIgEADQgGADgHAAQgGAAgFgBIgGgBIgDAAIAAABIgDAKIgCAGQgCAFgDACQgCADgEAAIgHgCg");
	this.shape_71.setTransform(469.4,43.9);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#444444").s().p("AhTAwQgJgDgFgGIgBACQgBABAAAAQAAABAAAAQgBAAAAAAQAAABAAAAIgFAAIAAAAIgDAAQgBgBAAAAQgBABgBAAQAAAAgBAAQAAABgBAAQAAABgBAAQAAABAAAAQgBABAAAAQAAAAgBAAIgDAAQgFAAgFgBIgBAAIAFgCIANgEIALgGIABgBIAEgLQAIgPAKgIQAVgKAIAAIAKAAQAHgBABgBQADgCABgEQAFgFAJADIAHADIAGACQAHAEAFABQAEAAACgBQAEgCAAgDIgBgIIAAgEIACgFIACgEQAEgEAGgDIAKgEQAJAAAIAHIAFAEQAIAGAIgCIALgEIADgCQAIgFAFABQABAAAAAAQABABAAAAQABAAAAABQAAAAABABIABABIABADIgBACIAAAEIgCAFIAAABIAAACQAAAEADABIACAAIADAAIAGAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAIABADQAAACgEADQgHAFgLACIgHACIgQADIgJAAIgFgBIgQgDIgLgBIgHAAIgIAAQgHAAgDAEQgDACgBACIgDAFQgEAFgCgBIgEgDIgEgFIgCgDIgCgDQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAIAEgDIAAgCQgBgEgFgCIgKgBQgKABgHAEIgDADIgGAEIgGAEQgEACgDAEIgBACIACAAIAFgDQAEgCAEABQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIgBACQAAABAAAAQAAAAAAABQABAAAAAAQAAAAAAAAIACABIABgBIACABIgBABIgBADIgCABIgEADQgFACgHAAIgIgBIgDAKIgBAFQgCAGgDACQgCACgEAAIgHgBg");
	this.shape_72.setTransform(475.6,43.9);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#444444").s().p("AhQAwQgKgDgFgHIAAAAIgFAHQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBAAIgEgBIAAAAIgDABIgEAAIgCACIgDAAIgJgCIgBAAIAFgCIAKgEIAKgGIAEgCIADgCIADgJQAIgPAJgHQAUgMAIABIAKAAQAGgBACgCQACgBACgFQAEgFAJADIAHADIAFADQAIAEAFAAQADABACgBQAFgCgBgDIgCgJIAAgEIACgFIADgEQADgEAGgDIAJgDQAJgBAIAIIAFADQAIAGAHgBIALgEIADgDQAIgEAFABIADADIACACIAAAEIAAACIAAAFIgBAFIgBABIAAACQABAFADABIADAAIADABIAGAAQAAABABAAQAAAAAAAAQABABAAAAQAAAAABABIABADQAAADgDADQgHAEgLAEIgHACIgPADIgJABIgGgBIgPgDIgLgCIgHgBIgIAAQgGAAgEAFQgDABgBADIgDAEQgDAFgDgCIgEgDIgEgGIgCgCIgCgDQAAgBAAAAQAAgBAAAAQABgBAAAAQABgBAAAAIADgEIAAgBQAAgFgEgCQgEgBgGAAQgKgBgHAFIgDACIgGADIgHAFIgGAGIgCAEIAEAAQABAAAAAAQABAAAAAAQAAAAABAAQAAABAAAAIAAABQAAAAAAABQAAAAAAAAQAAAAAAAAQAAAAAAAAIACAAIABAAIABAAIgBABIgBACIgBABIgEACIgIACIgCAJIgCAFQgCAGgCACQgCACgDAAIgIgCg");
	this.shape_73.setTransform(481.8,44);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#444444").s().p("AhNAyQgHgDgFgFIAAAAIgDAAIAAAAIgDABIgDABIgEAFIgBACIgEgBIgDAAIgDAAQgBAAAAABQAAAAAAAAQgBAAAAAAQAAAAAAAAIgDAAIgHgDIAAAAIADgCIAJgEIAHgFIAEgDIADgBIADAAIADAAIADgLQAGgQAJgGQAUgNAHABIAKAAQAHgBABgBQACgCACgEQAEgFAIADIAHADIAGADQAHADAFABIAFAAQAEgDAAgDIgDgIQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAgBIABgFIADgDQADgEAGgDIAJgEQAIgCAIAJIAFAEQAIAGAGgCIALgEIAEgCQAIgEAEABIAEAEIABACIABAEIAAADIAAAFIgBAGIAAABIAAACQABAFADACIADABIADAAIAGABQAAAAABABQAAAAABAAQAAABABAAQAAABAAAAIABAEQABACgEADQgGAHgLAEIgGACIgQADIgJABIgFgBIgPgCIgLgCIgGgBIgIgBQgHAAgEAEIgDAEIgDAEQgEAGgDgDIgEgEIgDgGIgCgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQACgCAAgDQAAAAABAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAgCgEgDQgDgCgHAAQgKgBgHAEIgDACIgGADIgHAFIgFAGIgFAKIgBAEIgCAJIgCAGQgBAGgDACQgCACgDAAQgDAAgEgCg");
	this.shape_74.setTransform(488,44);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#444444").s().p("AhtA1IgCAAIgDgBIgBABIgCgBIgGgEIAAABIACgDIAHgDIAGgFIACgDIADgBIACgBIADAAIAEgCIACgBIAAAAIABgBIACAAIABgHQAGgRAIgHQATgMAIAAIAJABQAHgBABgCIAEgGQADgFAJADIAGADIAGADQAHAEAFABQADAAACgBQAEgCgBgEIgDgIIgBgEQAAgDACgCIADgEQADgEAFgDIAJgEQAIgCAHAJIAFAEQAHAGAHgBIALgEIADgCQAIgFAFADIADADIABADIABAFIAAADIABAGIgBAGIAAAAIAAADQABAGAEACIACABIAEABIAGABQACABACADIABACQABAEgEAEQgGAHgLAFIgGABQgIADgHABIgJABIgFAAIgPgDIgLgCIgGgBIgHgBQgHgBgEAFQgCABgBADIgEAEQgDAFgDgDIgEgFIgDgGIgCgDQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAgBABgBQAAAAAAgBQABAAAAgBQABAAAAAAQACgDABgDIABgDQAAgFgDgBIgKgDQgLgBgHADIgEACIgGADIgGAFIgFAGQgDAGgCAIIgCAJIgCAFQgBAHgCACQgEAEgJgFQgHgDgFgGIgCACIgCADIgCABIAAABIgCAAIgCAAIgDABIgEAEIgBABIgEgBg");
	this.shape_75.setTransform(494.3,44.1);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#444444").s().p("AhqA4IgEgBIgBAAIgDgBIgBgBIgCgBIgEgEIACgCIAEgEIAEgEIADgDIABgBIACAAIACgBIADgCIACAAIAAAAIABgBIACAAIABAAIAFAAIADAAIACgKQAEgRAIgHQATgNAHABIAJABQAHgBABgCIADgGQADgFAJADIAGADIAGADQAGAEAFABQADAAACgBQAEgCgBgEIgEgIIAAgEIABgFIADgEIAIgHIAJgFQAHgCAHAJIAFAFQAHAGAGgBIALgEIADgCQAIgEAFACQACABABADIABADIABAGIAAADIABAGIAAAHIAAABIAAADQACAGADACIADACIADABIAHACQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAABIACAEQABAFgEAEQgFAJgLAEIgGACIgPAEIgJABIgFgBIgOgBIgLgDIgGgBIgHgCQgHAAgEAEQAAAAgBAAQgBABAAAAQAAABgBAAQAAABAAAAIgDAEQgEAFgDgDIgEgFIgDgHIgCgDQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgDADgCQACgCACgDQAAgBABAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgFgEgDIgJgCQgLgCgIADIgDABIgGADIgGAFIgFAHIgFAOIgCAIIgBAGQgBAGgCACQgDAEgJgEQgIgEgEgHIgBABIgCACIgBABIgDADIgDADIgCACIgBAAIgBABIgBAAIgCAAIgCABIgDACIgBAAIAAAAg");
	this.shape_76.setTransform(500.5,44.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},24).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11,p:{x:552.3,y:41.9}}]},1).to({state:[]},1).to({state:[{t:this.shape}]},5).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_11,p:{x:506.7,y:44.4}}]},1).to({state:[]},1).to({state:[{t:this.shape}]},21).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_11,p:{x:506.7,y:44.4}}]},1).to({state:[]},1).to({state:[{t:this.shape}]},8).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_40}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[{t:this.shape_45}]},1).to({state:[]},1).to({state:[{t:this.shape}]},51).to({state:[{t:this.shape_46}]},1).to({state:[{t:this.shape_47}]},1).to({state:[{t:this.shape_48}]},1).to({state:[{t:this.shape_49}]},1).to({state:[{t:this.shape_50}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_52}]},1).to({state:[{t:this.shape_53}]},1).to({state:[{t:this.shape_54}]},1).to({state:[{t:this.shape_55}]},1).to({state:[{t:this.shape_56}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_58}]},1).to({state:[{t:this.shape_59}]},1).to({state:[{t:this.shape_60}]},1).to({state:[{t:this.shape_61}]},1).to({state:[{t:this.shape_62}]},1).to({state:[{t:this.shape_63}]},1).to({state:[{t:this.shape_64}]},1).to({state:[{t:this.shape_65}]},1).to({state:[{t:this.shape_66}]},1).to({state:[{t:this.shape_67}]},1).to({state:[{t:this.shape_68}]},1).to({state:[{t:this.shape_69}]},1).to({state:[{t:this.shape_70}]},1).to({state:[{t:this.shape_71}]},1).to({state:[{t:this.shape_72}]},1).to({state:[{t:this.shape_73}]},1).to({state:[{t:this.shape_74}]},1).to({state:[{t:this.shape_75}]},1).to({state:[{t:this.shape_76}]},1).to({state:[{t:this.shape_11,p:{x:506.7,y:44.4}}]},1).to({state:[]},1).wait(52));
	this.timeline.addTween(cjs.Tween.get(this.shape).wait(24).to({_off:false},0).to({_off:true},1).wait(16).to({_off:false},0).to({_off:true},1).wait(32).to({_off:false},0).to({_off:true},1).wait(26).to({_off:false,x:412.5},0).to({_off:true},1).wait(70).to({_off:false,x:305.5,y:60.3},0).to({_off:true},1).wait(85));
	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(28).to({_off:false},0).to({_off:true},1).wait(16).to({_off:false,scaleX:0.5,scaleY:0.76,x:471},0).to({_off:true},1).wait(32).to({_off:false},0).to({_off:true},1).wait(26).to({_off:false,x:430},0).to({_off:true},1).wait(72).to({_off:false,scaleY:0.58,x:340,y:35.6},0).to({_off:true},1).wait(79));

	// door_hand
	this.instance = new lib.door_hand();
	this.instance.setTransform(558.2,42.8,1,1,0,0,0,3,1.8);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).to({x:576.7,y:46},9,cjs.Ease.get(1)).wait(162).to({x:558.2,y:42.8},22).wait(64));

	// door_open
	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f().s("#444444").ss(1,0,1).p("AjSEBIFCBCIBjpHIk7g+g");
	this.shape_77.setTransform(565.8,45.4);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#FFFFFF").s().p("AjSEAIBqpCIE7A/IhjJGg");
	this.shape_78.setTransform(565.8,45.4);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f().s("#444444").ss(1,0,1).p("Ai9EZIBupeIENBFIhiJGg");
	this.shape_79.setTransform(567.9,45);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#FFFFFF").s().p("Ai9EZIBupeIENBFIhiJGg");
	this.shape_80.setTransform(567.9,45);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f().s("#444444").ss(1,0,1).p("AirEvIBxp3IDmBKIhjJHg");
	this.shape_81.setTransform(569.7,44.7);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#FFFFFF").s().p("AirEvIBxp3IDmBKIhjJHg");
	this.shape_82.setTransform(569.7,44.7);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f().s("#444444").ss(1,0,1).p("AibFCIB0qNIDDBQIhiJHg");
	this.shape_83.setTransform(571.3,44.5);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#FFFFFF").s().p("AibFCIB0qNIDDBQIhiJHg");
	this.shape_84.setTransform(571.3,44.5);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f().s("#444444").ss(1,0,1).p("AiOFQIB4qfIClBUIhiJHg");
	this.shape_85.setTransform(572.6,44.4);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#FFFFFF").s().p("AgWlPIClBUIhjJHIi6AEg");
	this.shape_86.setTransform(572.6,44.4);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f().s("#444444").ss(1,0,1).p("AiDFXIB5qtICOBXIhjJHg");
	this.shape_87.setTransform(573.7,44.8);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#FFFFFF").s().p("AgKlWICOBXIhjJHIikAPg");
	this.shape_88.setTransform(573.7,44.8);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f().s("#444444").ss(1,0,1).p("Ah7FdIB7q5IB8BaIhjJHg");
	this.shape_89.setTransform(574.5,45.1);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#FFFFFF").s().p("AAAlcIB8BaIhjJHIiUAYg");
	this.shape_90.setTransform(574.5,45.1);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f().s("#444444").ss(1,0,1).p("Ah1FhIB7rBIBvBbIhiJIg");
	this.shape_91.setTransform(575.2,45.4);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#FFFFFF").s().p("AAGlgIBwBcIhjJHIiIAeg");
	this.shape_92.setTransform(575.2,45.4);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f().s("#444444").ss(1,0,1).p("AhxFjIB8rFIBnBcIhiJIg");
	this.shape_93.setTransform(575.5,45.5);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#FFFFFF").s().p("AALliIBnBcIhjJIIiAAhg");
	this.shape_94.setTransform(575.5,45.5);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f().s("#444444").ss(1,0,1).p("AhwFkIB+gjIBjpHIhlhdg");
	this.shape_95.setTransform(575.6,45.5);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#FFFFFF").s().p("AAMljIBlBdIhjJHIh+Ajg");
	this.shape_96.setTransform(575.6,45.5);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f().s("#444444").ss(1,0,1).p("Ah0FhIB6rBIBvBbIhiJIg");
	this.shape_97.setTransform(575.2,45.4);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#FFFFFF").s().p("AAGlgIBvBbIhiJIIiHAeg");
	this.shape_98.setTransform(575.2,45.4);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f().s("#444444").ss(1,0,1).p("Ah5FeIB6q7IB5BaIhjJHg");
	this.shape_99.setTransform(574.7,45.2);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#FFFFFF").s().p("AABldIB5BaIhjJHIiQAag");
	this.shape_100.setTransform(574.7,45.2);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f().s("#444444").ss(1,0,1).p("Ah9FbIB7q1ICABYIhiJIg");
	this.shape_101.setTransform(574.3,45.1);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#FFFFFF").s().p("AgClaICABZIhjJHIiYAVg");
	this.shape_102.setTransform(574.3,45.1);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f().s("#444444").ss(1,0,1).p("AiCFYIB7qvICKBXIhjJIg");
	this.shape_103.setTransform(573.9,44.9);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#FFFFFF").s().p("AgIlXICLBXIhjJIIihAQg");
	this.shape_104.setTransform(573.9,44.9);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f().s("#444444").ss(1,0,1).p("AiGFVIB5qpICUBWIhjJHg");
	this.shape_105.setTransform(573.4,44.7);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#FFFFFF").s().p("AgNlUICUBWIhjJHIiqAMg");
	this.shape_106.setTransform(573.4,44.7);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f().s("#444444").ss(1,0,1).p("AiLFSIB4qjICfBVIhjJHg");
	this.shape_107.setTransform(573,44.6);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#FFFFFF").s().p("AgSlRICeBVIhjJHIizAHg");
	this.shape_108.setTransform(573,44.6);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f().s("#444444").ss(1,0,1).p("AiPFPIB3qdICoBTIhiJIg");
	this.shape_109.setTransform(572.5,44.4);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#FFFFFF").s().p("AgYlOICoBTIhjJHIi8ADg");
	this.shape_110.setTransform(572.5,44.4);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f().s("#444444").ss(1,0,1).p("AiTFLIB2qXICyBSIhjJHg");
	this.shape_111.setTransform(572.1,44.4);

	this.shape_112 = new cjs.Shape();
	this.shape_112.graphics.f("#FFFFFF").s().p("AiTFLIB2qXICyBSIhjJHg");
	this.shape_112.setTransform(572.1,44.4);

	this.shape_113 = new cjs.Shape();
	this.shape_113.graphics.f().s("#444444").ss(1,0,1).p("AiYFGIB2qRIC7BQIhjJHg");
	this.shape_113.setTransform(571.6,44.4);

	this.shape_114 = new cjs.Shape();
	this.shape_114.graphics.f("#FFFFFF").s().p("AiYFGIB2qRIC7BQIhjJHg");
	this.shape_114.setTransform(571.6,44.4);

	this.shape_115 = new cjs.Shape();
	this.shape_115.graphics.f().s("#444444").ss(1,0,1).p("AicFAIB0qLIDFBPIhiJIg");
	this.shape_115.setTransform(571.2,44.5);

	this.shape_116 = new cjs.Shape();
	this.shape_116.graphics.f("#FFFFFF").s().p("AicFAIB0qKIDFBOIhiJHg");
	this.shape_116.setTransform(571.2,44.5);

	this.shape_117 = new cjs.Shape();
	this.shape_117.graphics.f().s("#444444").ss(1,0,1).p("AihE7IB0qFIDPBOIhjJHg");
	this.shape_117.setTransform(570.7,44.6);

	this.shape_118 = new cjs.Shape();
	this.shape_118.graphics.f("#FFFFFF").s().p("AihE7IB0qFIDPBOIhjJHg");
	this.shape_118.setTransform(570.7,44.6);

	this.shape_119 = new cjs.Shape();
	this.shape_119.graphics.f().s("#444444").ss(1,0,1).p("AilE2IBzp/IDYBMIhiJHg");
	this.shape_119.setTransform(570.3,44.6);

	this.shape_120 = new cjs.Shape();
	this.shape_120.graphics.f("#FFFFFF").s().p("AilE2IBzp/IDYBMIhiJHg");
	this.shape_120.setTransform(570.3,44.6);

	this.shape_121 = new cjs.Shape();
	this.shape_121.graphics.f().s("#444444").ss(1,0,1).p("AiqExIByp6IDjBLIhjJIg");
	this.shape_121.setTransform(569.8,44.7);

	this.shape_122 = new cjs.Shape();
	this.shape_122.graphics.f("#FFFFFF").s().p("AiqExIByp6IDjBLIhjJHg");
	this.shape_122.setTransform(569.8,44.7);

	this.shape_123 = new cjs.Shape();
	this.shape_123.graphics.f().s("#444444").ss(1,0,1).p("AiuErIBxpzIDsBKIhjJHg");
	this.shape_123.setTransform(569.4,44.8);

	this.shape_124 = new cjs.Shape();
	this.shape_124.graphics.f("#FFFFFF").s().p("AiuErIBxpzIDsBKIhjJHg");
	this.shape_124.setTransform(569.4,44.8);

	this.shape_125 = new cjs.Shape();
	this.shape_125.graphics.f().s("#444444").ss(1,0,1).p("AizEmIBwptID3BIIhjJHg");
	this.shape_125.setTransform(569,44.9);

	this.shape_126 = new cjs.Shape();
	this.shape_126.graphics.f("#FFFFFF").s().p("AiyEmIBvptID3BIIhjJHg");
	this.shape_126.setTransform(569,44.9);

	this.shape_127 = new cjs.Shape();
	this.shape_127.graphics.f().s("#444444").ss(1,0,1).p("Ai3EgIBwpmID/BGIhiJHg");
	this.shape_127.setTransform(568.5,44.9);

	this.shape_128 = new cjs.Shape();
	this.shape_128.graphics.f("#FFFFFF").s().p("Ai3EgIBwpmID/BGIhjJHg");
	this.shape_128.setTransform(568.5,44.9);

	this.shape_129 = new cjs.Shape();
	this.shape_129.graphics.f().s("#444444").ss(1,0,1).p("Ai7EbIBuphIEKBGIhjJHg");
	this.shape_129.setTransform(568.1,45);

	this.shape_130 = new cjs.Shape();
	this.shape_130.graphics.f("#FFFFFF").s().p("Ai7EbIBupgIEKBFIhjJGg");
	this.shape_130.setTransform(568.1,45);

	this.shape_131 = new cjs.Shape();
	this.shape_131.graphics.f().s("#444444").ss(1,0,1).p("AjAEWIBupbIETBEIhiJHg");
	this.shape_131.setTransform(567.6,45.1);

	this.shape_132 = new cjs.Shape();
	this.shape_132.graphics.f("#FFFFFF").s().p("AjAEWIBtpbIEUBEIhjJHg");
	this.shape_132.setTransform(567.6,45.1);

	this.shape_133 = new cjs.Shape();
	this.shape_133.graphics.f().s("#444444").ss(1,0,1).p("AjFERIBtpVIEdBDIhiJGg");
	this.shape_133.setTransform(567.2,45.1);

	this.shape_134 = new cjs.Shape();
	this.shape_134.graphics.f("#FFFFFF").s().p("AjEERIBtpVIEdBDIhjJGg");
	this.shape_134.setTransform(567.2,45.1);

	this.shape_135 = new cjs.Shape();
	this.shape_135.graphics.f().s("#444444").ss(1,0,1).p("AjJELIBspPIEnBCIhjJHg");
	this.shape_135.setTransform(566.7,45.2);

	this.shape_136 = new cjs.Shape();
	this.shape_136.graphics.f("#FFFFFF").s().p("AjJELIBspPIEnBCIhjJGg");
	this.shape_136.setTransform(566.7,45.2);

	this.shape_137 = new cjs.Shape();
	this.shape_137.graphics.f().s("#444444").ss(1,0,1).p("AjNEGIBrpJIEwBAIhiJHg");
	this.shape_137.setTransform(566.3,45.3);

	this.shape_138 = new cjs.Shape();
	this.shape_138.graphics.f("#FFFFFF").s().p("AjNEGIBrpJIEwBAIhiJHg");
	this.shape_138.setTransform(566.3,45.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_78},{t:this.shape_77}]},1).to({state:[{t:this.shape_80},{t:this.shape_79}]},1).to({state:[{t:this.shape_82},{t:this.shape_81}]},1).to({state:[{t:this.shape_84},{t:this.shape_83}]},1).to({state:[{t:this.shape_86},{t:this.shape_85}]},1).to({state:[{t:this.shape_88},{t:this.shape_87}]},1).to({state:[{t:this.shape_90},{t:this.shape_89}]},1).to({state:[{t:this.shape_92},{t:this.shape_91}]},1).to({state:[{t:this.shape_94},{t:this.shape_93}]},1).to({state:[{t:this.shape_96},{t:this.shape_95}]},1).to({state:[{t:this.shape_96},{t:this.shape_95}]},162).to({state:[{t:this.shape_98},{t:this.shape_97}]},1).to({state:[{t:this.shape_100},{t:this.shape_99}]},1).to({state:[{t:this.shape_102},{t:this.shape_101}]},1).to({state:[{t:this.shape_104},{t:this.shape_103}]},1).to({state:[{t:this.shape_106},{t:this.shape_105}]},1).to({state:[{t:this.shape_108},{t:this.shape_107}]},1).to({state:[{t:this.shape_110},{t:this.shape_109}]},1).to({state:[{t:this.shape_112},{t:this.shape_111}]},1).to({state:[{t:this.shape_114},{t:this.shape_113}]},1).to({state:[{t:this.shape_116},{t:this.shape_115}]},1).to({state:[{t:this.shape_118},{t:this.shape_117}]},1).to({state:[{t:this.shape_120},{t:this.shape_119}]},1).to({state:[{t:this.shape_122},{t:this.shape_121}]},1).to({state:[{t:this.shape_124},{t:this.shape_123}]},1).to({state:[{t:this.shape_126},{t:this.shape_125}]},1).to({state:[{t:this.shape_128},{t:this.shape_127}]},1).to({state:[{t:this.shape_130},{t:this.shape_129}]},1).to({state:[{t:this.shape_132},{t:this.shape_131}]},1).to({state:[{t:this.shape_134},{t:this.shape_133}]},1).to({state:[{t:this.shape_136},{t:this.shape_135}]},1).to({state:[{t:this.shape_138},{t:this.shape_137}]},1).to({state:[{t:this.shape_78},{t:this.shape_77}]},1).wait(64));

	// 圖層 8 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EhBjALiQABgXBxrUQBwrJgFgcUgAFgAaAr1ACdIUABJICLAIQdLBsdMBwIDYANIi0POQ9eAd9dAYIlNAEIw+ANQ3aAQr0AAQr+AAgBgRg");
	mask.setTransform(170.6,30.1);

	// car_body
	this.instance_1 = new lib.car();
	this.instance_1.setTransform(629.3,73.5,0.474,0.474,15,0,0,45,17.4);
	this.instance_1._off = true;

	this.instance_1.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(3).to({_off:false},0).to({regX:44.9,regY:17.6,scaleX:1,scaleY:1,x:547.2,y:56.9},7).to({rotation:-12.2,x:467.7,y:58.2},8).to({rotation:2.8,x:461.6,y:73},2).to({regY:17.5,rotation:6.5,x:445.6},2).to({regX:44.8,regY:17.6,rotation:0.1,x:444.1},2).to({rotation:-4.4,x:437.1,y:67.5},2).to({rotation:4.1,x:430.7,y:73.5},2).to({regX:44.7,rotation:-1.3,x:426.1,y:71},2).wait(4).to({regX:44.8,rotation:0.1,x:427.6,y:73},0).to({rotation:0,x:487.5,y:73.1},35,cjs.Ease.get(0.5)).to({x:442.5,y:73},12,cjs.Ease.get(1)).to({x:451.6},7).to({x:421.1},6).to({x:424.6},5).to({x:398.6},7).to({x:297.8,y:73.1},60).to({x:308.5,y:73},8).to({x:274.3},6).to({x:109.3,alpha:0},43,cjs.Ease.get(1)).wait(35));

	// door_inside
	this.instance_2 = new lib.door_inside();
	this.instance_2.setTransform(565.5,45,1,1,0,0,0,20.8,32.1);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({_off:false},0).wait(257));

	// door_close
	this.instance_3 = new lib.door_close();
	this.instance_3.setTransform(565.5,45,1,1,0,0,0,20.8,32.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(258));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = rect = new cjs.Rectangle(844.2,57.4,42.8,65.4);
p.frameBounds = [rect, new cjs.Rectangle(843.7,57,44.3,66.7), new cjs.Rectangle(844.2,56.9,43.3,66.4), new cjs.Rectangle(844.2,56.3,46.1,67), new cjs.Rectangle(844.2,55.8,46.1,67.5), new cjs.Rectangle(844.2,55.3,46.1,68.3), new cjs.Rectangle(834.2,55,56.1,69.8), new cjs.Rectangle(816,54.7,71.5,70.9), new cjs.Rectangle(797.8,54.5,89.7,71.7), new cjs.Rectangle(779.7,54.4,107.8,72.1), new cjs.Rectangle(760.4,45.1,127.6,82.2), new cjs.Rectangle(750.3,53.9,137.7,73.4), new cjs.Rectangle(739.1,53.9,148.9,73.4), new cjs.Rectangle(728.3,53.9,159.7,73.4), new cjs.Rectangle(717.9,53.9,170.1,73.4), new cjs.Rectangle(707.7,53.9,180.3,73.4), new cjs.Rectangle(697.9,53.9,190.1,73.4), new cjs.Rectangle(687.6,53.9,200.4,73.4), new cjs.Rectangle(672.6,53.9,215.4,73.4), new cjs.Rectangle(674.9,53.9,213.1,73.4), new cjs.Rectangle(672.1,53.9,215.9,73.4), new cjs.Rectangle(664.6,53.9,223.4,73.4), new cjs.Rectangle(656.5,53.9,231.5,73.4), new cjs.Rectangle(655.6,53.9,232.4,73.4), new cjs.Rectangle(654.6,53.9,233.4,73.4), new cjs.Rectangle(651,53.9,237,73.4), new cjs.Rectangle(645.2,53.9,242.8,73.4), new cjs.Rectangle(644.3,53.9,243.7,73.4), new cjs.Rectangle(641.3,53.9,246.7,73.4), new cjs.Rectangle(639,53.9,249,73.4), rect=new cjs.Rectangle(635.8,53.9,252.2,73.4), rect, rect, rect, new cjs.Rectangle(638.1,53.9,249.9,73.4), new cjs.Rectangle(640.6,53.9,247.4,73.4), new cjs.Rectangle(643.1,53.9,244.9,73.4), new cjs.Rectangle(645.6,53.9,242.4,73.4), new cjs.Rectangle(647.9,53.9,240.1,73.4), new cjs.Rectangle(650.3,53.9,237.7,73.4), new cjs.Rectangle(652.6,53.9,235.4,73.4), new cjs.Rectangle(654.8,53.9,233.2,73.4), new cjs.Rectangle(657,53.9,231,73.4), new cjs.Rectangle(659.2,53.9,228.8,73.4), new cjs.Rectangle(661.3,53.9,226.7,73.4), new cjs.Rectangle(663.3,53.9,224.7,73.4), new cjs.Rectangle(665.3,53.9,222.7,73.4), new cjs.Rectangle(667.2,53.9,220.8,73.4), new cjs.Rectangle(669.1,53.9,218.9,73.4), new cjs.Rectangle(671,53.9,217,73.4), new cjs.Rectangle(672.8,53.9,215.2,73.4), new cjs.Rectangle(674.6,53.9,213.4,73.4), new cjs.Rectangle(676.3,53.9,211.7,73.4), new cjs.Rectangle(677.9,53.9,210.1,73.4), new cjs.Rectangle(679.6,53.9,208.4,73.4), new cjs.Rectangle(681.1,53.9,206.9,73.4), new cjs.Rectangle(682.6,53.9,205.4,73.4), new cjs.Rectangle(684.1,53.9,203.9,73.4), new cjs.Rectangle(685.5,53.9,202.5,73.4), new cjs.Rectangle(686.9,53.9,201.1,73.4), new cjs.Rectangle(688.3,53.9,199.7,73.4), new cjs.Rectangle(689.5,53.9,198.5,73.4), new cjs.Rectangle(690.7,53.9,197.3,73.4), new cjs.Rectangle(691.9,53.9,196.1,73.4), new cjs.Rectangle(693,53.9,195,73.4), new cjs.Rectangle(694.1,53.9,193.9,73.4), new cjs.Rectangle(695.1,53.9,192.9,73.4), new cjs.Rectangle(696.1,53.9,191.9,73.4), new cjs.Rectangle(697,53.9,191,73.4), new cjs.Rectangle(697.9,53.9,190.1,73.4), new cjs.Rectangle(690.7,53.9,197.3,73.4), new cjs.Rectangle(684.2,53.9,203.8,73.4), new cjs.Rectangle(678.3,53.9,209.7,73.4), new cjs.Rectangle(673,53.9,215,73.4), new cjs.Rectangle(668.3,53.9,219.7,73.4), new cjs.Rectangle(664.2,53.9,223.8,73.4), new cjs.Rectangle(660.8,53.9,227.2,73.4), new cjs.Rectangle(658,53.9,230,73.4), new cjs.Rectangle(655.8,53.9,232.2,73.4), new cjs.Rectangle(654.2,53.9,233.8,73.4), new cjs.Rectangle(653.3,53.9,234.7,73.4), new cjs.Rectangle(653,53.9,235,73.4), new cjs.Rectangle(654.3,53.9,233.7,73.4), new cjs.Rectangle(655.6,53.9,232.4,73.4), new cjs.Rectangle(656.9,53.9,231.1,73.4), new cjs.Rectangle(658.2,53.9,229.8,73.4), new cjs.Rectangle(659.5,53.9,228.5,73.4), new cjs.Rectangle(660.8,53.9,227.2,73.4), new cjs.Rectangle(662.1,53.9,225.9,73.4), new cjs.Rectangle(657,53.9,231,73.4), new cjs.Rectangle(651.9,53.9,236.1,73.4), new cjs.Rectangle(646.8,53.9,241.2,73.4), new cjs.Rectangle(641.7,53.9,246.3,73.4), new cjs.Rectangle(636.7,53.9,251.3,73.4), new cjs.Rectangle(631.6,53.9,256.4,73.4), new cjs.Rectangle(632.3,53.9,255.7,73.4), new cjs.Rectangle(633,53.9,255,73.4), new cjs.Rectangle(633.6,53.9,254.4,73.4), new cjs.Rectangle(634.3,53.9,253.7,73.4), new cjs.Rectangle(635,53.9,253,73.4), new cjs.Rectangle(631.3,53.9,256.7,73.4), new cjs.Rectangle(627.6,53.9,260.4,73.4), new cjs.Rectangle(623.9,53.9,264.1,73.4), new cjs.Rectangle(620.2,53.9,267.8,73.4), new cjs.Rectangle(616.5,53.9,271.5,73.4), new cjs.Rectangle(612.7,53.9,275.3,73.4), new cjs.Rectangle(609,53.9,279,73.4), new cjs.Rectangle(607.3,53.9,280.7,73.4), new cjs.Rectangle(605.7,53.9,282.3,73.4), new cjs.Rectangle(604,53.9,284,73.4), new cjs.Rectangle(602.3,53.9,285.7,73.4), new cjs.Rectangle(600.6,53.9,287.4,73.4), new cjs.Rectangle(598.9,53.9,289.1,73.4), new cjs.Rectangle(597.3,53.9,290.7,73.4), new cjs.Rectangle(595.6,53.9,292.4,73.4), new cjs.Rectangle(593.9,53.9,294.1,73.4), new cjs.Rectangle(592.2,53.9,295.8,73.4), new cjs.Rectangle(590.6,53.9,297.4,73.4), new cjs.Rectangle(588.9,53.9,299.1,73.4), new cjs.Rectangle(587.2,53.9,300.8,73.4), new cjs.Rectangle(585.5,53.9,302.5,73.4), new cjs.Rectangle(583.8,53.9,304.2,73.4), new cjs.Rectangle(582.2,53.9,305.8,73.4), new cjs.Rectangle(580.5,53.9,307.5,73.4), new cjs.Rectangle(578.8,53.9,309.2,73.4), new cjs.Rectangle(577.1,53.9,310.9,73.4), new cjs.Rectangle(575.4,53.9,312.6,73.4), new cjs.Rectangle(573.8,53.9,314.2,73.4), new cjs.Rectangle(572.1,53.9,315.9,73.4), new cjs.Rectangle(570.4,53.9,317.6,73.4), new cjs.Rectangle(568.7,53.9,319.3,73.4), new cjs.Rectangle(567,53.9,321,73.4), new cjs.Rectangle(565.4,53.9,322.6,73.4), new cjs.Rectangle(563.7,53.9,324.3,73.4), new cjs.Rectangle(562,53.9,326,73.4), new cjs.Rectangle(560.3,53.9,327.7,73.4), new cjs.Rectangle(558.6,53.9,329.4,73.4), new cjs.Rectangle(557,53.9,331,73.4), new cjs.Rectangle(555.3,53.9,332.7,73.4), new cjs.Rectangle(553.6,53.9,334.4,73.4), new cjs.Rectangle(551.9,53.9,336.1,73.4), new cjs.Rectangle(550.3,53.9,337.7,73.4), new cjs.Rectangle(548.6,53.9,339.4,73.4), new cjs.Rectangle(546.9,53.9,341.1,73.4), new cjs.Rectangle(545.2,53.9,342.8,73.4), new cjs.Rectangle(543.5,53.9,344.5,73.4), new cjs.Rectangle(541.9,53.9,346.1,73.4), new cjs.Rectangle(540.2,53.9,347.8,73.4), new cjs.Rectangle(538.5,53.9,349.5,73.4), new cjs.Rectangle(536.8,53.9,351.2,73.4), new cjs.Rectangle(535.1,53.9,352.9,73.4), new cjs.Rectangle(533.5,53.9,354.5,73.4), new cjs.Rectangle(531.8,53.9,356.2,73.4), new cjs.Rectangle(530.1,53.9,357.9,73.4), new cjs.Rectangle(528.4,53.9,359.6,73.4), new cjs.Rectangle(526.7,53.9,361.3,73.4), new cjs.Rectangle(525.1,53.9,362.9,73.4), new cjs.Rectangle(523.4,53.9,364.6,73.4), new cjs.Rectangle(521.7,53.9,366.3,73.4), new cjs.Rectangle(520,53.9,368,73.4), new cjs.Rectangle(518.4,53.9,369.6,73.4), new cjs.Rectangle(516.7,53.9,371.3,73.4), new cjs.Rectangle(515,53.9,373,73.4), new cjs.Rectangle(513.3,53.9,374.7,73.4), new cjs.Rectangle(511.6,53.9,376.4,73.4), new cjs.Rectangle(510,53.9,378,73.4), new cjs.Rectangle(508.3,53.9,379.7,73.4), new cjs.Rectangle(509.6,53.9,378.4,73.4), new cjs.Rectangle(510.9,53.9,377.1,73.4), new cjs.Rectangle(512.3,53.9,375.7,73.4), new cjs.Rectangle(513.6,53.9,374.4,73.4), new cjs.Rectangle(514.9,53.9,373.1,73.4), new cjs.Rectangle(516.3,53.9,371.7,73.4), new cjs.Rectangle(517.6,54.5,369.9,71.8), new cjs.Rectangle(518.9,54.7,368.6,71.1), new cjs.Rectangle(513.2,54.8,374.3,70.5), new cjs.Rectangle(507.5,54.9,380,69.9), new cjs.Rectangle(501.9,55.1,385.6,69.4), new cjs.Rectangle(496.2,55.2,391.3,68.8), new cjs.Rectangle(490.5,55.4,397,68.1), new cjs.Rectangle(484.8,55.5,402.7,67.7), new cjs.Rectangle(477.2,55.7,410.3,67.6), new cjs.Rectangle(469.8,55.8,417.7,67.4), new cjs.Rectangle(462.6,56,424.9,67.3), new cjs.Rectangle(455.5,56.1,432,67.2), new cjs.Rectangle(448.6,56.2,438.9,67), new cjs.Rectangle(441.9,56.4,445.6,66.9), new cjs.Rectangle(435.4,56.5,452.1,66.7), new cjs.Rectangle(429.1,56.7,458.4,66.6), new cjs.Rectangle(422.9,56.8,464.6,66.4), new cjs.Rectangle(417,57,470.5,66.3), new cjs.Rectangle(411.2,57.1,476.3,66.2), new cjs.Rectangle(405.5,57.2,482,66), new cjs.Rectangle(400.1,57.4,487.4,65.9), new cjs.Rectangle(394.8,57,493.2,66.7), new cjs.Rectangle(389.7,57,498.3,66.7), new cjs.Rectangle(384.8,57,503.2,66.7), new cjs.Rectangle(380.1,57,507.9,66.7), new cjs.Rectangle(375.5,57,512.5,66.7), new cjs.Rectangle(371.2,57,516.8,66.7), new cjs.Rectangle(367,57,521,66.7), new cjs.Rectangle(363,57,525,66.7), new cjs.Rectangle(359.1,57,528.9,66.7), new cjs.Rectangle(355.5,57,532.5,66.7), new cjs.Rectangle(352,57,536,66.7), new cjs.Rectangle(348.7,57,539.3,66.7), new cjs.Rectangle(345.6,57,542.4,66.7), new cjs.Rectangle(342.6,57,545.4,66.7), new cjs.Rectangle(339.9,57,548.1,66.7), new cjs.Rectangle(337.3,57,550.7,66.7), new cjs.Rectangle(334.9,57,553.1,66.7), new cjs.Rectangle(332.6,57,555.4,66.7), new cjs.Rectangle(330.6,57,557.4,66.7), new cjs.Rectangle(328.7,57,559.3,66.7), new cjs.Rectangle(327,57,561,66.7), new cjs.Rectangle(325.5,57,562.5,66.7), new cjs.Rectangle(324.1,57,563.9,66.7), new cjs.Rectangle(323,57,565,66.7), new cjs.Rectangle(322,57,566,66.7), new cjs.Rectangle(321.2,57,566.8,66.7), new cjs.Rectangle(320.6,57,567.4,66.7), new cjs.Rectangle(320.1,57,567.9,66.7), new cjs.Rectangle(319.9,57,568.1,66.7), rect=new cjs.Rectangle(319.8,57,568.2,66.7), rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect, rect];

})(car_ani = car_ani||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var car_ani, images, createjs, ss;