(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 40,
	height: 40,
	fps: 24,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.動態2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#444444").s().p("AgdALQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAAAAAAAQABgBAAAAIA8gRQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAARQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAg");
	this.shape.setTransform(9.4,8.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#444444").s().p("AADAhIgPg+QAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBABAAIAVgCQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIgGA/QAAABAAAAQgBAAAAABQAAAAAAAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQAAgBAAAAg");
	this.shape_1.setTransform(1.4,3.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#444444").s().p("AgWAnQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAABAAIAdhJQAAgBABgBQAAAAAAAAQABAAAAAAQABAAAAABIAPARQAAAAAAABQABAAAAAAQAAABgBAAQAAAAAAABIgsA4IgCAAIAAAAg");
	this.shape_2.setTransform(6.5,4.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,12.7,9.3);


(lib.hand2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#444444").s().p("AgFAHIAAgEIAAgFIAAgDIABAAIABgBIABABIACABIAGAEQAAAAAAAAQABAAAAAAQAAAAgBAAQAAAAAAABQAAACgDADIgBABIAAAAIgEAAg");
	this.shape.setTransform(0.7,2.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#444444").s().p("AAAAHIgEgCIgCAAIABgHIAAgDIABgBIADABIAEADIAEACIgBADQgBADgEABg");
	this.shape_1.setTransform(10,2.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#444444").s().p("AgEAMQgCgFAAgDIABgCIABgBIAAgBIgBgKIgCgGIABgBIAAAAIAFAEQAEAGADAGIACADIAAAFIgCAEIgFAGIgBAAQgCgBgCgEg");
	this.shape_2.setTransform(5.7,1.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10.7,3.6);


// stage content:
(lib.hand_ani = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 圖層 2
	this.instance = new lib.動態2();
	this.instance.setTransform(32.1,2.4,1,1,0,0,0,6.4,4.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({_off:false},0).to({_off:true},3).wait(4).to({_off:false},0).to({_off:true},3).wait(23));

	// hand2
	this.instance_1 = new lib.hand2();
	this.instance_1.setTransform(25.1,21.5,1,1,0,0,0,5.4,9.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regY:9.2,scaleY:1.11,rotation:6.2,x:25.6,y:21.6},2).to({regY:9.1,scaleY:1,rotation:0,x:25.1,y:21.5},2).wait(3).to({regY:9.2,scaleY:1.11,rotation:6.2,x:25.6,y:21.6},2).to({regY:9.1,scaleY:1,rotation:0,x:25.1,y:21.5},2).wait(26));

	// 圖層 1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Ag3DeIhjhuQgDgGgRiLQgPiMACgGQACgECSgXICQgWIB5FeIhgAnIgLgWIhUAdIADAcIgFAig");
	mask.setTransform(22.7,19.1);

	// hand
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#444444").ss(1.4,1,1).p("AhRhzIgDghIAFgFQAGgEAFABQAKACACAAQAHADABAHQADAMAKAfIgLgtIAHgHQAIgGAJAGQAKAHABABIALAmIgGgfIAGgBQAIgBAGADQAJADAMASIAIALIgHgQIAQAFQAQAGAFAGQAFAIAFANQAFAMAAAEIAGAhIAAApQAAAGgBAVQAAAUADAJIAVA2IhjApQgahQgPgKQgRgLgxgxQgNgLgCgZIgHhJQABgGAAgEQABgHgCgGQgEgMAAgEQgCgJAGABQANAAAIAKQADAEAEAMQACAEAAADQACAHAAADIAAABQgBAFAEAcQACAPACAOIgHg+");
	this.shape.setTransform(24,22.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgXBEQgRgLgxgxQgNgLgCgZIgHhJIABgKQABgHgCgGIgEgQQgCgJAGABQANAAAIAKQADAEAEAMIACAHIACAIIAAACIAAABIAAAAIADAhIAEAdIgHg+IAAgBIAAgCIgCgIIgDghIAFgFQAGgEAFABIAMACQAHADABAHQADAMAKAfIgLgtIAHgHQAIgGAJAGIALAIIALAmIgGgfIAGgBQAIgBAGADQAJADAMASIAIALIgHgQIAQAFQAQAGAFAGQAFAIAFANQAFAMAAAEIAGAhIAAApIgBAbQAAAUADAJIAVA2IhjApQgahQgPgKgAhMhHIgDghIAAAAIAHA+IgEgdgAhPhog");
	this.shape_1.setTransform(24,22.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#444444").ss(1.4,1,1).p("AA5h5QADAAADABQADABACABQADACACADQAFAGADAKQABACABADQAAABAAABQABAEABADQABADAAACQAAABAAABIAAABIAEAgIAAAAQAAABAAAAQAAADABAEAA5h5QADAAACABQADABADABQADACADADQAEAHADAJQABACABACQAAACAAABQABAFABADQABACAAACAgHiSQACACAAABIAHAdIAAgBIABAAIgDgLIAAgIIAAgBIABgEQABgBABAAQACgBADAAIACAAQABABACAAQAFAAAFAEQAGAEAIAKQADAFACAFIAFAJIABAAIgGgRIADgDIAHABQACAAADABAgMiXQABABACABQABACABABAgTibQADABACACQABAAABABQABABABABQACACABABQABACABABIAHAeIABgBIgBgBIgCgLIAAgJIAAAAIABgEQAAgBABAAQADgBADAAAgliZIABAAQACgCADgCQAFgCAGADQAAAAABABQACABACABQABABACABAgliZQADgCAEgCQAEgBAFACQABAAABABAgliGIgDgLIABgFIABgBIAAAAIABgBQAAgBAAAAAgmiXIABgCAgfhqQAAAAAAABIAAAAIgDgMIgDgRIgDgKIACgHAgoiIIABAGQADAJAEANQAAABABABIgDgLAAKiNQACAAACABQAEAAAFADQAGAEAIALQADAFACAEIAFAKIABABIAAAAIgGgRIAEgEIAFABQADAAADABABagrQAAABABABQAAACAAAEIAAACQAAABAAAAIAAABQABAIAAAGIAAABIgCAMQAAADAAABIAAABQgBACAAACQgBAJgBAKQAAABAAABIAAACQAAAEABAEIABAJQAAACABACQABAEABADQADAKADAJQAIAUAGASQgCADgBADIgBAAIgGADIhUAlQgCAAgBgBQgGgVgJgTQgOgngOgIQgDgCgDgBQgMgFgQgQQgNgOgJgPQgDgDgCgEQgLgRgDgTQgCgGAAgEIAAgBQgBgCAAgDQAAgBAAgBQAAgLAAgSIAAgdQAAgCAAgCIAAAAQAAgDABgCIAAgDQAAgBAAgBIAAAAABaABIAAAAQgBACAAACABagEQAAADAAACAhLiaQABgBABgBQAFgCADAAQABAAABAAQABAAAAAAQADABACAAQACAAACABQADABACABQADACABADQAAABAAAAIABABQAAACABABQAAAEACAEAhLiaQACgBACgBQACgCADAAQACAAABAAQACAAABAAQABABACAAQADAAABABQADABABAAQAEADABAEAhtiJQgBgCAAgCIAAgBQgCgJAGABQAVAKAAAAQADAEAEAKQACAGAAACIgDgfIABgDQABAAAAgBIAAAAQABgBABAAAhtiJQgBgCAAgBIAAgBAhph4QAAgCAAgBQgBgDgBgCQgBgFgBgEAhph4QAAgCAAgCQgBgCAAgBQgCgGgBgEAhphxQAAgBAAgBQAAgCAAgCIAAgBAgriTQAAACABACQAAADACAEAhNiZQABAAABgBAhKhqQAAgBAAgCQAAgCgBgDQAAgCgBgEIgDgbIACgGAhMh2QABAGAAACQAAAHABAMIABAGIAAABQABAFABAGIgBgEIAAAAIgBgTIgBgIQAAgBAAgBAhJhgIgBgKAhJhUQABAEAAADAhIhNQABABAAABQACAQACAOIgGgzAhKhoQAAAEAAAJABZAtQAAACABACQAAADABADQAEALADAJQAIAUAFARQgBAEgCADIAAAAIgGAD");
	this.shape_2.setTransform(24.3,22);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAPCeQgGgVgJgTQgOgngOgIIgGgDQgMgFgQgQQgNgOgJgPIgFgHQgLgRgDgTIgCgKIAAgBIgBgFIAAgCIAAgdIAAgdIAAgEIAAAAIABgFIAAgDIAAgCIAAAAIAAgEIAAgBIAAgEIgBgDIgDgKIgBgDIAAgBIAAgBQgCgJAGABIAVAKIAHAOIACAIIgDgfIABgDIABAAIAAgBIACgBIgCACIACgCIACgCQAFgCADAAIACAAIAAAAIAAAAIgDAAQgDAAgCACIgEACIAEgCQACgCADAAIADAAIAAAAIAAAAIADAAIADABIAEABIAFACQADACABADIAAABIABABIABADIACAIIgCgHIgBgEIABAEIACAHIABAGIAHAXIABABIAAABIAAAAIgDgMIgDgQIgDgLIACgHIABgCIAHgEQAEgBAFACIACABIAEACIADACIACACIADADIACADIAHAeIABgBIgBAAIABgBIgDgLIAAgIIAAAIIAAgIIAAAAIABgFIACgBIAFgBIACAAIADABQAFAAAFAEQAGAEAIAKIAFAKIAFAJIABABIAAAAIgGgRIAEgEIAFABIAGABIAGABIAFACIgGgCIgFgBIAFABIAGACIAGAFQAEAHADAJIACAFIAAADIACAHIABAEIAAACIAAABIAEAgIAAAAIAAABIABAHIAAACIAAABIAAABIABAOIAAABIgCAMIAAAEIAAABIgBAEIABgEIAAgBIAAgEIAAAFIAAAAIgBAEIgCATIAAACIAAACIABAIIABAKIABADIABAGIAHAUIANAlIgDAHIADgHIgNglIgHgUIgBgGIgBgDIABADIACAHIAGATIAOAmIgDAGIgBAAIgGADIhUAlIgDgBgAhHhLIAEAeIgGgzIABATIgBgHIAAgBIgBgGIgBgTIgBgIIABAIIABATIABAGIAAABIACALIgBgEIABACgAhKhbIAAgNIABAIIgBgKIAAgDIgBgFIgBgGIgDgbIACgFIgCAFIADAbIABAGIABAFIAAADIABAKIgBgIIAAgCIAAACIAAANgABJhxQAFAGADAKQgDgKgFgGIgFgFIAFAFgAg+ieIAFABIgFgBIgBAAIABAAgAhHhLIgBgCIAAAAIgBgTIAGAzIgEgegAhJhUIABAHIAAAAIABAEIgCgLgAAqhwIgFgKQgIgKgGgEQgFgEgFAAIgDgBIAEABQAEAAAFADQAGAEAIALIAFAJIAFAKgAAAh+IADALIgBABgAhph7IgCgFIgCgJIADAKIABADIAAAEIAAgDgAgsiVQgBgDgDgCIgFgCIgEgBIAEABIAEABQAEADABAEIAAgBgAgmiXIABgBIAAgBIgBACgAgMiXIAAAAgAgPiZIgEgCIAFADIACABIgDgCgAgliZg");
	this.shape_3.setTransform(24.3,22);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#444444").ss(1.4,1,1).p("AhHh3IgEgiIAFgEQAGgEAFAAQAKACACABQAHADABAHQADALAKAgIgLguIAHgHQAIgFAJAGIALAIIAKAlIgHgeIAIgBQAIgBAGACQAJAEAMASIAJAVIgJgdIASgCQATAGACAhIADAoQABADABAJQACAJgBAGQAAACgEASQgEAOAAAHQAAAIAEARQADAPAFAMQAKAaAFAWIhfAtQgGgVgIgWQgUgsgUgEQgNgCgPgRQgPgQgEgQQgRgrgBgLQgBgHADgfIACghQABgGAAgEQABgHgCgGQgEgNAAgDQgCgJAGAAQANABAIAJQADAEAEAMIADAIQABAIAAACIAAAAQgBAGAEAbIAEAeIgHg/");
	this.shape_4.setTransform(24.7,21.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgBB3QgUgsgUgEQgNgCgPgRQgPgQgEgQQgRgrgBgLQgBgHADgfIACghIABgKQABgHgCgGIgEgQQgCgJAGAAQANABAIAJQADAEAEAMIADAIIABAIIAAACIAAAAIAAACIADAfIAEAeIgHg/IAAAAIAAgCIgBgIIgEgiIAFgEQAGgEAFAAIAMADQAHADABAHQADALAKAgIgLguIAHgHQAIgFAJAGIALAIIAKAlIgHgeIAIgBQAIgBAGACQAJAEAMASIAJAVIgJgdIASgCQATAGACAhIADAoIACAMQACAJgBAGIgEAUQgEAOAAAHQAAAIAEARQADAPAFAMQAKAaAFAWIhfAtQgGgVgIgWgAhDhMIgDgfIAAgCIAHA/gAhGhtg");
	this.shape_5.setTransform(24.7,21.8);

	this.shape.mask = this.shape_1.mask = this.shape_2.mask = this.shape_3.mask = this.shape_4.mask = this.shape_5.mask = mask;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_1},{t:this.shape}]},3).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_1},{t:this.shape}]},1).wait(26));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(31.3,25.4,25.5,33.6);

})(hand_ani = hand_ani||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var hand_ani, images, createjs, ss;